(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 1280,
	height: 720,
	fps: 24,
	color: "#FFFFFF",
	webfonts: {},
	manifest: []
};



lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



// stage content:
(lib.main_block_line_removed = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// bush_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#011001").s().p("EhMMAStMhvDAAAQAAgNgagUQgagUhfhlQhfhmBJkfQBJkgA1hhQCJj6GKgTQB4gWBqA3QAZANAOAPQgDhMAUhSQAGgdASgVQCFigDSgRIAFABQAnAMAkAPQARAHANALQgNhcAahsQA8j6D9AFQCIAsBwBjQALAKAJAMQABg9Arg7QBjiKCPgoQClAZB9BxQAZAXAXAZQARgQATgQQCKhxC2gZQCdAoBtCKQAvA7ABA9QAKgMAMgKQB8hjCWgsQEWgFBCD6QAdBsgPBcQAPgLASgHQApgPAqgMIAGgBIACAAQAtgMAygEIAFABQAnAMAkAPQARAHANALQgNhcAahsQA8j6D9AFQCIAsBwBjQALAKAJAMQABg9Arg7QBjiKCPgoQClAZB9BxQAZAXAXAZQARgQATgQQCKhxC2gZQCdAoBtCKQAvA7ABA9QAKgMAMgKQB8hjCWgsQEWgFBCD6QAdBsgPBcQAPgLASgHQApgPAqgMIAGgBQDoARCSCgQATAVAIAdQAVBRgDBNQAQgPAbgNQB1g3CEAWQGFAEBZFfQAQBAAPCRQAQCRhpDuQhmDqqqAAIgaAAgEBAIANDQhWgehThmQhUhmANjiQANjjC3joQC3jrGKgTQB4gYBrA5QAYANAPAPQgDhOAThSQAHgdARgVQCFigDSgRIAGABQAmAMAlAPQAQAHAOALQgNhcAahsQA8j6D8AFQCIAsBxBjQALAKAJAMQABg9Aqg7QBjiKCbgGQCZgJB9BxQAaAXAWAZQAKgJB5hSQB5hSCMAVQCNAVBEBjQBEBjACA9QAKgNBUhFQBThGB2gNQEXgFBCD6QAcBsgOBcQAPgLASgHQAogPArgMIAGgBIABAAQAugMAxgEIAGABQAmAMAlAPQAQAHAOALQgNhcAahsQA8j6D8AFQCIAsBxBjQALAKAJAMQABg9Aqg7QBjiKCPgoQClAZB9BxQAaAXAWAZQARgQAUgQQCJhxC2gZQCeAoBtCKQAuA7ACA9QAJgMANgKQB8hjCVgsQEXgFBCD6QAcBsgOBcQAPgLASgHQAogPArgMIAGgBQDnARCTCgQATAVAHAdQAWBSgEBOQAQgPAbgNQB1g5CFAYQGEAEBZFdQAQBAAPDNIAJCKQAKCrAKDvIAAAJIgdAAMhv1AAAQisABiMAAQoCAAhEgXg");
	this.shape.setTransform(644.7,720);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// bush_2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#021A02").s().p("EA0rAOlQhqgChUhUQhRhQgJhkQgdlIGbBxQgyjeCOhJQCFhDCHBBQAJhxAlhEQAkhHCyheQCxhfECCRQgHhwAjhRQAjhTCbhJQCbhJDPCxQALhPAjhmQAjhnBwh1QByh3EAgZQDCgWCFBDQCEBDBSCAQBjiUCchAQCchBCdAwQCcAvBwB0QBvByAPBWQANBPACBPQC/jTDTCWQAuAhAVA9QAlBmgGBuQENi3D1DFQAZATARAnQAyBngGB5QB1hCByBEQB7BJATCOQEmgigaFJQgPDAi6ASQk1Ae4AAIQ57AKhLADQncAUmFAEQiFACiLAAQkxAAlRgIgEiHvANsQjggSgSjAQgflIFhAhQAXiOCUhJQCKhECMBCQgGh4A7hoQAVgnAegTQEnjFFEC3QgIhvAthlQAag+A3ggQD+iWDmDTQADhQAQhUQAQhVCHhtQCGhtEEARQBjAPBiAiQB6AqBKCZQC7i0BGgTQBHgSBBgOQDtASC6CPQA8AuAPBVQAOBOADBQQDSjTDoCWQAyAgAYA+QApBlgHBvQEoi3ENDFQAbATAUAnQA2BogGB4QCAhCB+BEQCHBJgbDOQFyhhgcFIQgIBjg3A2Qg6A5hkAAMgqXAAOIpLABQ7qAAlYgcg");
	this.shape_1.setTransform(615.1,650.8);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// bus
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0C0C0C").s().p("APzFBQhegXAEhzQAUg7A4gXQANgFANAAQB9gEATBiQADBdhAAfQgaAMgeAAQgTAAgUgFgAP6CVQgNADgIAIIgNAKQgMAUACAgIAAADQANAmAqAMQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABQAvACAWgYIACgBQAIgLAFgPIACAAIABgeIgBgDQgPgygyAAQgPAAgRAEgAoTFBQhdgYAGh1QAUg0AwgXQASgJATAAQB7gDASBmQgBBZhAAeQgaAMgdAAQgTAAgUgFgAovDrQACAHAFAHQAQATAaAJQBFABAPg1IACAAIAAgeIAAgCQgLgcgZgQIgBgBQgLgBgIgFIgBgBQhgABASBdgAOIBPIjJAAIgDAAIAAgGIAAi3IAAgDIAAAAQBlgCBnAAIAAACIACAAIgBDAgAK/hrIAAC3IACAAIDFAAIAAgCIAAi4IjFAAIgCAAIAAADgAxpAfIAAgiIbyAAIAAAigAxmgvIAAgkIbxAAIAAAkgAPRh8IgDAAIAAgDIAAjBIADAAIDGAAQABBggBBhIAAADIjGAAgALBiBIgCAAIAAgDIAAjBIACAAIDHAAIAADBIAAADIjHAAgAHQiBIgBAAIAAjCIAAgCIABAAIDFAAIAAAFIAAADIAAC0IAAACIAAADIAAADIjFAAgADliBIgCAAIAAgDIAAi/IACAAIDFAAIAAC/IAAADIjFAAgAgJiBIgDAAIAAgDIAAi/IADAAIDCAAIAAC/IAAADIjCAAgAj5iBIgDAAIAAgDIAAi/IADAAIDGAAIAAC/IAAADIjGAAgAnkiBIgDAAIAAgDIAAi8IgCAAIAAgDIACAAQBlACBfgEIACAAIAADBIAAADIjDAAgArXiBIgDAAIAAgDIAAi/IADAAIDEAAIAAC/IAAADIjEAAgAvFiBIgCAAIAAgDIAAjBIACAAIDGAAIAADBIAAADIjGAAgAyUiBIgCAAIAAjCIAAgCIACAAICiAAIAAAFIAAADQgEBYADBeIABAAIAAADIAAADIiiAAg");
	this.shape_2.setTransform(1129.1,538.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(0,0,0,0.996)").s().p("ASJEhIgCAAQgBghgEghQgHgrAqAIIADAAIADAAIAfAAIAABiIAAADIhBAAgATdhiQgEgdAAgcQABgcgEgaIgwgdIgCgBIAAgMIACAAIAwAdIAAgBQAKgKAXAEIAAADIAACIIgMABQgNAAgBgJgAFqkRInVAAInWAAInWAAIjeAAIAAgDQgCgJAEgDQBrAEBxAAQDrgCDrAAIHWAAIHVAAIL9AAIAAAKIAAADImiABg");
	this.shape_3.setTransform(1136.3,530.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(83,71,30,0.608)").s().p("Ag4AAIAAAAIACAAIAtAAIADAAIA/AAIAAABIhxgBg");
	this.shape_4.setTransform(1253.2,559.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FDBE2E").s().p("AhgBeIgCAAIAAi4IAAgDIACAAIDDAAIAAC4IAAADIjDAAg");
	this.shape_5.setTransform(1209.4,536.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("rgba(34,36,36,0.71)").s().p("AgNA8IgCAAIAAh4QADAbAAAcQAAAaAEAcQACANAWgFQgKAEgMAAIgHgBg");
	this.shape_6.setTransform(1261.8,515.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("rgba(9,9,9,0.2)").s().p("AAABDIAAiFIABAAIgBCFg");
	this.shape_7.setTransform(1263.6,514.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("rgba(180,149,35,0.714)").s().p("AgIAeIACgCQAFAAABgBQAKgWgEgjIADAAQADAkgMAXQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAgBAAg");
	this.shape_8.setTransform(1256.1,500.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("rgba(148,122,28,0.588)").s().p("An9AAIE5AAIHUAAQB3AAB3AAQh0ABh3AAQjsgBjpABIgjAAQiPAAiJgBg");
	this.shape_9.setTransform(1145,559.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FCFCFC").s().p("ALxBDQAAAAAAAAQAAgBAAAAQgBAAAAAAQAAAAAAAAQgpgMgOgnIAAgCQgCgfANgTIANgLQAHgHANgDQBOgTATBBIABADIgBAbIgBAAQgGAPgIAMIgCABQgUAVgpAAIgHAAgAsTBDQgagJgPgSQgGgHgBgIQgThbBgAAIABABQAIAEAMACIAAABQAZAPALAcIAAADIAAAbIgCABQgOAzhDAAIgDAAg");
	this.shape_10.setTransform(1156.8,559.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#C8982F").s().p("AAABiQgBhkAChgIAAADIAAACIAAC8IAAADg");
	this.shape_11.setTransform(1103.6,515.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#B38B2F").s().p("AAABiIAAgDIAAi+IAAgDIABAAIgBDEg");
	this.shape_12.setTransform(1076.2,515.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#181F2F").s().p("AAABfIAAgDIAAi6IABAAIAAC6IAAADIgBAAg");
	this.shape_13.setTransform(1080.2,515.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#65542F").s().p("AAAheIAAgCIABAAIAAACIAAACIAAC6IAAADQgCheABhhg");
	this.shape_14.setTransform(1079.9,515.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#735D2F").s().p("AAABhIAAgDIAAi8IAAgCIABAAIgBDBg");
	this.shape_15.setTransform(1147.8,515.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#A7812F").s().p("AAABiQgChkADhgIAAADIAAC+IAAADg");
	this.shape_16.setTransform(1151.5,515.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#0F192F").s().p("AhjBhIAAgDIAAi+IACAAIDFAAIAAACIjCAAIgDAAIAAC8IAAADIgCAAg");
	this.shape_17.setTransform(1161.7,515.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#D4A02F").s().p("AAABiIAAgDIAAi8IAAgCIAAgDIABAAIgBDEg");
	this.shape_18.setTransform(1124,515.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#0E192F").s().p("AlOAAIgDAAIAAAAIADAAIDEAAQhCABhEAAIg+gBgACOAAIgDAAIAAAAIADAAIDEAAIAAAAIjEAAgAhhAAIgCAAIAAAAIACAAIDFAAIAAAAIjFAAg");
	this.shape_19.setTransform(1113.8,506);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#443E2F").s().p("AAAheIAAgCIABAAIAAACIAAC8IAAADQgCheABhhg");
	this.shape_20.setTransform(1127.7,515.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#A37E2F").s().p("AysgBIDbAAIHXAAIHWAAIHUAAIL9AAIAAABIr9AAInUAAInWAAQjrAAjsABIgWABQhlAAhggDg");
	this.shape_21.setTransform(1129.2,501.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#35342F").s().p("AAABbQgChcADhZIAACzIAAACg");
	this.shape_22.setTransform(1027.9,515.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("rgba(221,168,46,0.996)").s().p("AKFABInWgBInVAAInWAAIjhAAIAAAAIDfAAIHWAAIHUAAIHXAAIFaAAQieABiMAAIguAAg");
	this.shape_23.setTransform(1108.2,503.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#94732F").s().p("ANDBiIAAgDIAAi+IAAgDIACAAIgBDEgAtEBiIAAgDIAAi+IAAgDIADAAIgBDEg");
	this.shape_24.setTransform(1112,515.6);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#0C182F").s().p("ANDBhIAAgDIAAgCIAAgCIAAizIAAgDIAAgEIACAAIAAC+IAAADIgCAAgAtEBhIAAgDIAAgCIAAgCIAAizIAAgDIAAgEIACAAIAAC+IAAADIgCAAg");
	this.shape_25.setTransform(1111.8,515.7);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#8C6E2F").s().p("AOVABIjFAAIgBAAIAAgBIDIAAIAAABIgCAAgAHjABIgDAAIAAgBIADAAIDHAAIAAABIjHAAgAAFABIgDAAIAAgBIADAAIDGAAIAAABIjGAAgAnXABIgDAAIAAgBIDKAAIAAABIjHAAgAryABIiiAAIgCAAIAAgBICnAAIAAABIgDAAg");
	this.shape_26.setTransform(1103.5,505.8);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#101A2F").s().p("ABiBhIAAgDIAAi8IjDAAIgCAAIAAgCIACAAIDFAAIAAC+IAAADIgCAAg");
	this.shape_27.setTransform(1066.1,515.7);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#E6AD2E").s().p("AAABhQgChjADheIAAACIAAC8IAAADg");
	this.shape_28.setTransform(1055.9,515.7);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#8D6F2F").s().p("ALjABIgDAAIgCAAIAAgBIDLAAIAAABIjGAAgADbABIjEAAIgDAAIgCAAIAAgBIDLAAIAAABIgCAAgAkBABIjEAAIgDAAIgCAAIAAgBIDLAAIAAABIgCAAgAujABIgDAAIgCAAIAAgBIDLAAIAAABIjGAAg");
	this.shape_29.setTransform(1125.7,505.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("rgba(253,190,45,0.996)").s().p("AGHE0InUAAIk5AAIAAgDIAAgJQgTh5iUAFQgbABgUALQg7AfgKBNIgBABIoyAAIAAixIgBAAIAAhxIAAkHIDhAAIHWAAIHXAAIHUABQCgABC4gDIGigBIAAgDIAAgKIAAgCIr9AAInUAAInWAAInXAAIjbAAIAAgDQANgbAcgKIDnAAIHWAAIHWAAIHVAAIMWAAQADAkgMAWQAAACgFAAIgDACIAAAMIAAADIAAAMIAAAEQgCA7AHFsIgDAAQgqgIAGArQAEAhABAhIgtAAIgCAAIAAgDIAAgMQgUh4iWAIQgTABgPAHQhFAfgJBYIjoACQh3gCh4AAgAKVgNIAAABIAAADIAAC3IAAAGIACAAIDJAAIACAAIABjAIgDAAIAAgCQhmAAhlABgAyQCEIbyAAIAAgkI7yAAgAyNA0IbxAAIAAgkI7xAAgAOngaIAAACIADAAIDGAAIAAgCQABhhgBhhIjGAAIgDAAIAADCgAKVjiIAAABIAAADQgCBjAEBeIADAAIDGAAIAAgDIAAjBIAAgCIjLABgAGnjiIAAABIAAADIAADBIACAAIDFAAIACAAIABAAIABjGIgCAAIjJABgAC4gdIABAAIADAAIACAAIDEAAIAAgDIAAi+IAAgDIAAgCIjGAAIgDAAQgEBgADBmgAg1jiIAAABIAAADQgCBjAEBeIADAAIDCAAIABAAIABjEIAAgCIjJABgAkkgdIABAAIACAAIDHAAIACAAIAAjGIgCAAIjHAAIgCAAQgEBgADBmgAoTjiIAAABIAAADQgCBjAEBeIADAAIADAAIDDAAIAAgDIAAjBIAAgCIjLABgAsBjiIAAABQgFBfAEBlIABAAIADAAIDEAAIACAAIACAAIABjGIgDAAIjJABgAvxjiIAAABIAAADQgCBjAEBeIADAAIDGAAIAAgDIAAjBIAAgCIjLABgAy+jiIAAABIAAADIAADBIADAAICiAAIADAAIABAAIACjGIgDAAIioABg");
	this.shape_30.setTransform(1133,528.5);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#876A2F").s().p("ANDheIAAgCIACAAIAAC+IAAADQgFheADhhgAtEheIAAgCIADAAIAAC+IAAADQgFheAChhg");
	this.shape_31.setTransform(1115.7,515.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2}]}).wait(1));

	// tree
	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#6A4D1A").s().p("AhGINIgRgEQADgKAJgIIAMgKQAFhBABhCIAAAAQAAgMgDgMIgDgMIgFgTQgRgXgOgaIgGgLIgRgdIgCgEQgdgugvgSIAIABQBDATAqA1QANAQAKATIAEAHIAAgFIAAgCIgBghIAAgRQgIg8gOg7QgCgIAAgJIgFgKQgDgEgCgFIAAgDQgRgigWgeQgNgRADgOQghgpgbgsQghg1gxgmQgEgEAFAAQB4BRBICCIALAPQATAdANAeIAFgSQAwjUghjWQgNhRgqhDIACgBQB5CyghDkQgOB5gZB0IAEAXQBCipCrhZQAcgOAcgKIAQgGQAJAPghANQgPAGgOAIQihBYhCCgQgDAsgCAvIgBAgIAAAhQAHgRAKgQQANgTAQgRQAVgXAZgTQAHgFAIgCQAGAPgaAZIgBABQgVAVgPAXQgYAlgMArIAAADQgDALgEAKIABAxQABAqAFAsQADAXAXAEQgbAIgcgBQgIADgJAAQgRAAgSgJg");
	this.shape_32.setTransform(980.6,488.9);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#573F0E").s().p("AgpFZQgngEgigGQgBAAAAgBQAAAAAAAAQABAAAAgBQABAAAAAAQA1gbgKg9QgDgRAAgRQAAgogJgnIgEgSIgEgMIgJgdIgRgVQgYgbgggVQABgBAAAAQAAgBAAAAQABgBAAAAQABAAAAAAIAHgBQAkAXAfAdIAHAHIgBgHQgFgqgLgnIgBgGQgghUg3g/IACgCIACgBQAnAZAYAqIAQAbIAMAXQgKhwAJhvQACgdAIgYQAIA4gBA+QgBBWAEBTQAThlA7hYQAcgtAIgyQAFA3gcA3QgaA3gYA5QgGAPgEAQIAEBQIACASQADgTANgVIAPgXQANgXASgSQAYgfAfgYQBQg8AnhWQABAkgZAjQg1BLhFA+QgPAOgKASQgQAegMAdIACAmIARgaQAVgbAegNIAKgJQAJgIALgBQgtAngfA2IgBABIgXApIgBAZIAAAOQgBBVATBSQAFARAJANIADgBQABAAAAAAQABAAgBAAQAAABAAAAQgBAAgBABIgBABIABABIgEAAQgYANgdAAIgMAAg");
	this.shape_33.setTransform(849,509.5);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#7A540A").s().p("Ag5GLIgkgBQAvhXgWhpIgBgHQgPhFgmg7QgRgdgigOQAqgEAkAnIAYAdQgMgyAMg6QAfifAWijQADgXAFgVIAAAAIACgIIAAANQARA5gQA8QgMAqACAsQAuhZBbgrQAZgMAWADIABAAIAAAAIAGABIgHACQgDAFgGAFIgIAEQgPAPgWASQgTARgTAMIABgDQhMBQgYB2QgXBsAzBjQA2gBAhgwQAQgYASgMQgQBDgpA7QgNATgQATIgLANQgYAZgCAlQgCAwAuAIQgiAXg1AAIgQAAg");
	this.shape_34.setTransform(139.7,505);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#003300").s().p("EhABAIOQApg7AQhDQgSAMgQAYQghAwg2ABQg1hjAWhuQAZh1BOhRIgBADQASgMAUgRQAWgSAPgPIAIgEQAGgFADgFIAGgCIgFgBIAAAAIgBAAQgWgCgZALQhbArgxBZQgBgsAMgqQARg6gSg5IAAgNIgCAIIAAAAQgFAVgDAXQgWChggCfQgMA8ANAyIgZgdQgjgngqAEQAhAOASAdQAlA7APBFQgoAVg5gCQivgJhkiEQgWgegOgkQhHizCNiLQAugrA0gjQAHgnAFgpQAPh3BkhIQBCgxBTgGQBrADBXA2QBVA1AkBbQARAqADAnQByA2A1B4QAgBGgDBUQgBBAgdA5QguBdhYA5QgPALgSAHQhIAghGAAQgsAAgsgNgEAtoAHMIAZgoIAAgCQAfg3AugoQgMACgJAHIgKAJQgeAOgUAcIgTAbIgCgmQANgfAQgeQAKgTAQgOQBFg+A1hLQAYgjgBgjQgnBVhPA8QggAZgXAeQgTASgOAXIgPAYQgOAVgDAUIgBgUIgEhQQAEgQAGgPQAXg5Acg2QAcg3gFg3QgHAxgfAuQg7BXgTBmQgEhUAChWQAAg9gHg5QgJAYgCAdQgIBwAKBvIgNgXIgPgbQgZgpgmgaIgCABIgDADQA4A+AfBUIABAGQALAqAGAqIAAAHIgHgHQgfgdgkgYIgGABQgBABAAAAQgBAAAAAAQAAABgBAAQAAABAAAAQAgAWAYAbIAQAVIAKAcIADANIgDgBIg8gZQgNgMgbgJQgSgGgRgJQgqgYgYgqIgkg9QgshJAEhaQAEhdAnhOQAyhoBfhFQBHgzBbALQCKApBsBgQAvApAPA8QAaBiAGBlQABAVgIAUQgqBvhUBMIgLAJIgQAMQhJAzhhACIACgZgEBCVAEpQBCiiChhYQAOgIAPgGQAhgOgJgPIgQAHQgcAJgcAOQirBahECrIgEgXQAZh3AQh4QAhjih7iyIgCABQAqBDANBQQAjDXgyDTIgFASQgNgegTgcIgLgSQhIiBh4hPQgFAAAEADQAxAnAhAzQAbAsAhApQgDAOANARQAWAgARAiIAAACQACAGADADIAFAKQAAAJACAJQAOA7AIA8IAAARIgagCQgqg2hDgSIgIgBQAvASAdAuIACADQgGgBgFgEIhAgyIglgdQg6gWgkg3QgJgOgLgOQhHhagYhyQgGgegJgfQgPg1AHg4QAOhvBAhYQBFhgBuglQAbgJAegDQBQgHBNgDQCaAYCJBNQAuAaAfAtQBEBkgOB9QgPCJgqCAQgcBUhAA8Qg+A5hLAgQgbAMgdAHIABgBQAagZgGgPQgIABgHAGQgZATgVAXIggADIgPABQACgvAFgsg");
	this.shape_35.setTransform(556.4,472.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32}]}).wait(1));

	// arch
	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f().s("#999999").ss(0.5,1,1).p("ACLkpIAnhmAFLjqIA4hRAJjgxIA3gwALgBHIAygjIARgMAObEwIAogRAPuGpIAnAAANLDFIAvgWAHciaIA3hAAmhkxIAnBNAihksIgehjAgEmoIAABtAtvCWIAmAdAwUGpIArAAAvCEfIAjASApuiXIAuA4AsBACIAqAn");
	this.shape_36.setTransform(640.3,516.3);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#B7362B").s().p("AOuFyQgpg7grg3Qgpg1gogwQgUgZgUgWQgkgpgkgmQlKlXlgABQlqAAk0FTQgmAogkAuIgjAtQgnAygnA3QgkAzgkA5Ig5AAQAOgZAxhNIALgSQAog+APgVIAggqIABgCIAtg6IAjgrIAfggIABgCQAeggAMgMQAWgWBNg/IAKgIQBLg+AfgTIACgCQAtgcAtgWQAxgYAZgIIAogOQAPgFBYgWIAZgFQAPgDAcgDIAxgDIApAAQA4ABAdAEIAeAGIAcAGIAfAHQBEAQAhAMIAAACIA7AaQBDAeAgAUIAuAfQA0AjAYATIAAAAIAsAlIAPAOQAmAgASASIAQAPQAAABA1A1IADADQAUAVAUAXIAHAIIA6BIIAQAUQAXAcAWAfIATAbIATAcQArA/AUAeg");
	this.shape_37.setTransform(640.4,521.8);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("APuGpQgUgfgrg/IgTgbIAngRIgnARIgUgcQgVgegXgdIgQgUIAugWIguAWIg7hIIgHgHQgTgXgVgWIgCgCIAxgjIgxAjQg2g4ABgBIgQgOQgTgRglggIA3gwIg3AwIgQgNIgsglIAAgBQgYgTgzgjIA3hAIg3BAIgugfQghgThCgeIA4hRIg4BRIg8gbIAAgBQgggMhEgQIgggHIAnhmIgnBmIgcgHIgdgFQgegFg4gBIAAhtIAABtIgpAAIgxAEQgbACgQADIgYAGIgehjIAeBjQhZAVgOAGIgoANQgZAIgxAYIgnhNIAnBNQguAWgsAdIgDACQgeAShLA+Igug4IAuA4IgKAIQhNBAgWAVQgNAKgdAhIgqgnIAqAnIgBABIggAjIgjArIgtA5IgBACIgmgdIAmAdIgfAqQgPAWgoA+IgjgSIAjASIgMASQgxBNgOAZIgqAAQANgZBFhxIBTiJIAPgYQAQgWAtg7IAigrIARgUQAlgrAmgmQAJgKAugqIAMgKQBDg8AggXIACgCQAughAugaQAzgeA1gVIADgCQAmgQBRgZIAzgLQArgJAmgCIA3gDIAEAAQBNACBLARIAaAGIADABQBLASBIAjQACgBAUALIADACIAiASQAqAZBAAqIAOAMIADACIAVAQIAwAoQArAkAAABIgBABIAKAJIACACIAhAgIAJAJQAhAjAiAmIACAAIADAHIAEAFIACACIAgAlIABACIAxA9IAJAMIACACIAWAfIAWAfQAdArAdAsIAGAJIABADIAIANIAAAAIAVAjIgBgDQAfAzAfA3g");
	this.shape_38.setTransform(640.3,516.3);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#D03F33").s().p("AQXIKQgfg3gfgzIABADIgVgjIAAAAIgIgMIgCgEIgFgJQgdgsgdgrIgWgfIgXgfIgCgCIgJgMIgwg9IgBgBIASgNIgSANIgggoIgCgCIgFgFIgDgHIgBAAQgjgmghgjIgJgHIggggIgCgCIgLgJIACgBQgBgBgqgkIgwgoIgWgQIgCgCIgPgMQhAgqgpgZIgigSIgDgCQgVgLgBABQhJgjhKgSIgEgBIgagGQhLgRhMgCIgEAAIg3ADQgmADgrAIIg0ALQhQAZgmAQIgEACQg1AWgzAdQguAagtAhIgDACQgfAXhEA8IgLALQguApgKAKQgmAkgkArIgSAWIgiArQgtA7gQAWIgOAYIhUCJQhEBxgOAZIg7AAQBzjYB8ilIAAoaIACAAIAAgiIi4AAIAAhaMAg0AAAIAABaIi5AAIAAJRQB3CeBzDKgALsAQIAoAtIAAnsIgoAAIAAAtIACAAIAAEQIgCAAgAsRAuIAjgpIAAm0IgjAAgAKkg6IAAl1I1IAAIAAAtIACAAIAAE6QErkiFWgYIAKAAQFuAAFNFIgAMMIKIAAjYQAoAwApA2IAABygAKcIKIAAlWQAkAmAkAqIAAEGgAr2IKIAAkDQAkguAmgoIAAFZgAtnIKIAAhtQAng3AngyIAADWg");
	this.shape_39.setTransform(640.1,506.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36}]}).wait(1));

	// pillar
	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AAKAdIgHgNIgEgIIgCgDIgGgBIgCAAIAAAZIgKAAIAAg5IAVAAQAHAAADABQADACADAEQACAEAAAFQAAAHgDAEQgDADgHABIAFAFIAGAKIAGALgAgLgDIAIAAIAHgBIACgCIABgFIgBgFQAAAAAAgBQgBAAAAAAQgBgBAAAAQgBAAAAAAIgGAAIgIAAg");
	this.shape_40.setTransform(657.2,416.7);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgJAcQgEgCgCgDQgCgDAAgEIgBgPIAAgeIAKAAIAAAeIAAAKQAAAEADACQADACACAAQAEAAACgCQACgCABgDIABgKIAAgfIAJAAIAAAdIgBAQQAAAEgCADQgCADgEACQgEACgGAAQgFAAgEgCg");
	this.shape_41.setTransform(652,416.7);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AgNAZQgFgFgBgKIAKgBQABAGADACQACADADAAQAFAAACgCQADgDAAgDIgBgEIgEgCIgGgDQgIgCgDgCQgFgFAAgHQAAgEACgEQACgEAFgCQAEgCAEAAQAJAAAFAFQAEAFABAIIgLAAQAAgEgCgCQgDgCgDAAQgDAAgDACQAAAAAAABQgBAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABABAAQAAABAAAAQACACAGACIAKAEQAEACACACQACAEAAAGQAAAFgCAEQgDAFgEACQgFACgGAAQgIAAgFgFg");
	this.shape_42.setTransform(647,416.7);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AgNAZQgFgFgBgKIAKgBQABAGADACQACADADAAQAFAAACgCQADgDAAgDIgBgEIgEgCIgGgDQgIgCgDgCQgFgFAAgHQAAgEACgEQACgEAFgCQAEgCAEAAQAJAAAFAFQAEAFABAIIgLAAQAAgEgCgCQgDgCgDAAQgDAAgDACQAAAAAAABQgBAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABABAAQAAABAAAAQACACAGACIAKAEQAEACACACQACAEAAAGQAAAFgCAEQgDAFgEACQgFACgGAAQgIAAgFgFg");
	this.shape_43.setTransform(642.4,416.7);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AgEAdIAAg5IAIAAIAAA5g");
	this.shape_44.setTransform(639.2,416.7);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AAKAdIgHgNIgEgIIgDgDIgFgBIgCAAIAAAZIgKAAIAAg5IAVAAQAHAAADABQADACADAEQACAEAAAFQAAAHgEAEQgDADgGABIAFAFIAGAKIAGALgAgLgDIAHAAIAIgBIACgCIABgFIgBgFQAAAAAAgBQgBAAAAAAQgBgBAAAAQgBAAAAAAIgGAAIgIAAg");
	this.shape_45.setTransform(635.9,416.7);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AAKAdIAAgaIgSAAIAAAaIgLAAIAAg5IALAAIAAAXIASAAIAAgXIAKAAIAAA5g");
	this.shape_46.setTransform(630.6,416.7);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AgDAdIAAgvIgPAAIAAgKIAlAAIAAAKIgOAAIAAAvg");
	this.shape_47.setTransform(625.9,416.7);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("AgRAdIAAg5IAjAAIAAAKIgZAAIAAANIAXAAIAAAIIgXAAIAAAQIAaAAIAAAKg");
	this.shape_48.setTransform(693.2,407.1);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#000000").s().p("AgKAaQgGgEgDgHQgDgHAAgIQAAgIADgHQAEgHAGgEQAFgDAFAAQAJAAAFAEQAGAFABAIIgKACQgBgEgDgCQgDgDgEAAQgFAAgEAFQgEAFAAAJQAAAJAEAGQAEAFAFAAIAGgBIAGgEIAAgIIgMAAIAAgIIAWAAIAAAWQgDAEgGADQgGACgHAAQgFAAgGgEg");
	this.shape_49.setTransform(688,407.1);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#000000").s().p("AgSAdIAAg5IAjAAIAAAKIgZAAIAAANIAYAAIAAAIIgYAAIAAAQIAbAAIAAAKg");
	this.shape_50.setTransform(683.1,407.1);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#000000").s().p("AgQAdIAAg5IAKAAIAAAvIAXAAIAAAKg");
	this.shape_51.setTransform(678.7,407.1);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#000000").s().p("AgQAdIAAg5IAKAAIAAAvIAXAAIAAAKg");
	this.shape_52.setTransform(674.5,407.1);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#000000").s().p("AgQAWQgHgIAAgOQAAgHADgGQABgFADgEQADgDAEgCQAEgCAFAAQALAAAGAIQAHAIAAANQAAAOgHAIQgGAIgLAAQgKAAgGgIgAgIgOQgEAFAAAJQAAAKAEAFQAEAFAEAAQAGAAADgFQAEgFAAgKQAAgJgDgFQgEgFgGAAQgFAAgDAFg");
	this.shape_53.setTransform(669.4,407.1);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#000000").s().p("AgOAWQgGgIAAgOQAAgNAGgIQAGgIAJAAQAJAAAGAGQADAEACAHIgKADQgBgFgDgCQgDgDgEAAQgDAAgEAFQgDAEAAAKQAAAKADAFQAEAFADAAQAEAAADgDQADgDABgHIAKAEQgCAKgFAFQgGAEgIAAQgIAAgGgIg");
	this.shape_54.setTransform(664.2,407.1);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#000000").s().p("AgKAaQgGgEgDgHQgDgHAAgIQAAgIADgHQAEgHAGgEQAFgDAFAAQAJAAAFAEQAGAFABAIIgKACQgBgEgDgCQgDgDgEAAQgFAAgEAFQgEAFAAAJQAAAJAEAGQAEAFAFAAIAGgBIAGgEIAAgIIgMAAIAAgIIAWAAIAAAWQgDAEgGADQgGACgHAAQgFAAgGgEg");
	this.shape_55.setTransform(657,407.1);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#000000").s().p("AAJAdIgSglIAAAlIgKAAIAAg5IALAAIASAlIAAglIAKAAIAAA5g");
	this.shape_56.setTransform(651.8,407.1);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#000000").s().p("AgDAdIAAg5IAIAAIAAA5g");
	this.shape_57.setTransform(648.3,407.1);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#000000").s().p("AAKAdIgIgNIgDgIIgDgDIgEgBIgDAAIAAAZIgKAAIAAg5IAVAAQAGAAAEABQAEACACAEQACAEAAAFQAAAHgEAEQgDADgGABIAFAFIAGAKIAGALgAgLgDIAHAAIAIgBIACgCIACgFIgCgFQAAAAAAgBQgBAAAAAAQgBgBAAAAQgBAAgBAAIgFAAIgIAAg");
	this.shape_58.setTransform(645,407.1);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#000000").s().p("AgSAdIAAg5IAjAAIAAAKIgZAAIAAANIAYAAIAAAIIgYAAIAAAQIAaAAIAAAKg");
	this.shape_59.setTransform(640,407.1);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#000000").s().p("AgSAdIAAg5IAjAAIAAAKIgZAAIAAANIAYAAIAAAIIgYAAIAAAQIAbAAIAAAKg");
	this.shape_60.setTransform(635.4,407.1);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#000000").s().p("AAJAdIgSglIAAAlIgKAAIAAg5IAKAAIATAlIAAglIAKAAIAAA5g");
	this.shape_61.setTransform(630.4,407.1);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#000000").s().p("AgDAdIAAg5IAIAAIAAA5g");
	this.shape_62.setTransform(627,407.1);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#000000").s().p("AgKAaQgGgEgDgHQgDgHAAgIQAAgIADgHQAEgHAGgEQAFgDAFAAQAJAAAFAEQAGAFABAIIgKACQgBgEgDgCQgDgDgEAAQgFAAgEAFQgEAFAAAJQAAAJAEAGQAEAFAFAAIAGgBIAGgEIAAgIIgMAAIAAgIIAWAAIAAAWQgDAEgGADQgGACgHAAQgFAAgGgEg");
	this.shape_63.setTransform(623.2,407.1);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#000000").s().p("AAJAdIgSglIAAAlIgKAAIAAg5IALAAIASAlIAAglIAKAAIAAA5g");
	this.shape_64.setTransform(618,407.1);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#000000").s().p("AgSAdIAAg5IAjAAIAAAKIgZAAIAAANIAYAAIAAAIIgYAAIAAAQIAaAAIAAAKg");
	this.shape_65.setTransform(613.2,407.1);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#000000").s().p("AgDAFIAAgJIAHAAIAAAJg");
	this.shape_66.setTransform(607.9,409.5);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#000000").s().p("AgDAdIAAgvIgPAAIAAgKIAlAAIAAAKIgOAAIAAAvg");
	this.shape_67.setTransform(605.6,407.1);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#000000").s().p("AgEAdIgSg5IALAAIALAqIAMgqIALAAIgSA5g");
	this.shape_68.setTransform(601.1,407.1);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#000000").s().p("AgQAWQgHgIAAgOQAAgHADgGQABgFADgEQADgDAEgCQAEgCAFAAQALAAAGAIQAHAIAAANQAAAOgHAIQgGAIgLAAQgKAAgGgIgAgIgOQgEAFAAAJQAAAKAEAFQAEAFAEAAQAGAAADgFQAEgFAAgKQAAgJgDgFQgEgFgGAAQgFAAgDAFg");
	this.shape_69.setTransform(596.1,407.1);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#000000").s().p("AgKAaQgGgEgDgHQgDgHAAgIQAAgIADgHQAEgHAGgEQAFgDAFAAQAJAAAFAEQAGAFABAIIgKACQgBgEgDgCQgDgDgEAAQgFAAgEAFQgEAFAAAJQAAAJAEAGQAEAFAFAAIAGgBIAGgEIAAgIIgMAAIAAgIIAWAAIAAAWQgDAEgGADQgGACgHAAQgFAAgGgEg");
	this.shape_70.setTransform(590.6,407.1);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#F2F253").s().p("AIsFdQAAAFhFAAQhGAAAAgFIAAldIsmAAIAAFdQAAAFhKAAQhLAAAAgFQAAAFgiAAQgiAAAAgFIAAnzIAAjMIS9AAIAAC0IAAAUIAAH3QAAAFgZAAQgaAAAAgFg");
	this.shape_71.setTransform(639.5,425.5);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#0E0E0E").s().p("AC8CaIAAh0ICIAAIAAB0gAg9CaIAAh0ICBAAIAAB0gAlDCaIAAh0ICYAAIAAB0gAC8AIIAAhNICIAAIAABNgAg9AIIAAhNICBAAIAABNgAlDAIIAAhNICYAAIAABNgAC8hkIAAg1ICIAAIAAA1gAg9hkIAAg1ICBAAIAAA1gAlDhkIAAg1ICYAAIAAA1g");
	this.shape_72.setTransform(640.9,445);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#981E1E").s().p("AFFCaIAAh0IAvAAIAAB0gACXCaIAAh0IAmAAIAAB0gABECaIAAh0IAmAAIAAB0gAheCaIAAh0IAiAAIAAB0gAirCaIAAh0IAhAAIAAB0gAlzCaIAAh0IAxAAIAAB0gAFFAJIAAhOIAvAAIAABOgACXAJIAAhOIAmAAIAABOgABEAJIAAhOIAmAAIAABOgAheAJIAAhOIAiAAIAABOgAirAJIAAhOIAhAAIAABOgAlzAJIAAhOIAxAAIAABOgAFFhjIAAg1IAvAAIAAA1gACXhjIAAg2IAmAAIAAABIAAA1gABEhjIAAg1IAAgBIAmAAIAAA2gAhehjIAAg2IAiAAIAAABIAAA1gAirhjIAAg1IAAgBIAhAAIAAA2gAlzhjIAAg2IAxAAIAAABIAAA1g");
	this.shape_73.setTransform(640.9,445);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#D03F33").s().p("AF0CuIAAh0IgvAAIiIAAIgmAAIAAB0IgtAAIAAh0IgmAAIiAAAIgiAAIAAB0IgsAAIAAh0IghAAIiXAAIgxAAIAAB0IgfAAIAAlbIMlAAIAAFbgACXAdIAmAAICIAAIAvAAIAAhOIgvAAIiIAAIgmAAgAheAdIAiAAICAAAIAmAAIAAhOIgmAAIiAAAIgiAAgAlzAdIAxAAICXAAIAhAAIAAhOIghAAIiXAAIgxAAgACXhPIAmAAICIAAIAvAAIAAg1IgvAAIiIAAIAAgBIgmAAgAhehPIAiAAICAAAIAmAAIAAg2IgmAAIAAABIiAAAIAAgBIgiAAgAlzhPIAxAAICXAAIAhAAIAAg2IghAAIAAABIiXAAIAAgBIgxAAg");
	this.shape_74.setTransform(640.8,443);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#35424B").s().p("AgBABIAAgBIADABg");
	this.shape_75.setTransform(578.5,554.2);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#66798F").s().p("ArNLTIlAAAIAAvkIAAhbIAAhiIAAiDIAAgnIAAhWQAAAHDTgBQDTABAAgHIAAH1QAAAGAiAAQAiAAAAgGIAAOsgAprLQIAFAAIgFgDgAKBLOIhdgBIAAumQAAAGAZAAQAaAAAAgGIAAn5QAAAGDbABQDcgBAAgGIAAD/IAABiIAABcIAAPjg");
	this.shape_76.setTransform(640.4,482.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40}]}).wait(1));

	// road
	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#003300").s().p("Eid4AN+IAA77ME7xAAAIAAb7g");
	this.shape_77.setTransform(701.5,726.3);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#006600").s().p("AB/BFIAAiJMCb1AAAIAACJgEidzABFIAAiJMCJUAAAIAACJg");
	this.shape_78.setTransform(702.6,540.3);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#333333").s().p("Eid7AIFIAQt9MCJUAAAIAAiMIWeAAIAACMMCb1AAAIgHN9g");
	this.shape_79.setTransform(701.8,585.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_79},{t:this.shape_78},{t:this.shape_77}]}).wait(1));

	// sub
	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#D03F33").s().p("Eg+pAQ+IAAlTIFKAAIAAFTgEg+NAQcIESAAIAAkOIkSAAgEA5gAQyIAAlTIFKAAIAAFTgEA58AQPIESAAIAAkOIkSAAgEg+pAHDIAAlTIFKAAIAAFTgEg+NAGgIESAAIAAkOIkSAAgEA5gAG2IAAlTIFKAAIAAFTgEA58AGUIESAAIAAkOIkSAAgEg+pgC2IAAlTIFKAAIAAFTgEg+NgDYIESAAIAAkOIkSAAgEA5ggDCIAAlTIFKAAIAAFTgEA58gDlIESAAIAAkOIkSAAgEg+pgLeIAAlTIFKAAIAAFTgEg+NgMAIESAAIAAkOIkSAAgEA5ggLqIAAlTIFKAAIAAFTgEA58gMNIESAAIAAkOIkSAAg");
	this.shape_80.setTransform(638.3,388.8);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#BFBF36").s().p("Eg+NAQcIAAkOIESAAIAAEOgEg7xAP+IBdAAIAAhYIhdAAgEg91AP+IBcAAIAAhYIhcAAgEg7xAN+IBdAAIAAhNIhdAAgEg91AN+IBcAAIAAhNIhcAAgEA58AQPIAAkOIESAAIAAEOgEA8aAPxIBcAAIAAhXIhcAAgEA6VAPxIBdAAIAAhXIhdAAgEA8aANyIBcAAIAAhOIhcAAgEA6VANyIBdAAIAAhOIhdAAgEg+NAGgIAAkOIESAAIAAEOgEg7xAGCIBdAAIAAhXIhdAAgEg91AGCIBcAAIAAhXIhcAAgEg7xAEDIBdAAIAAhOIhdAAgEg91AEDIBcAAIAAhOIhcAAgEA58AGUIAAkOIESAAIAAEOgEA8aAF2IBcAAIAAhYIhcAAgEA6VAF2IBdAAIAAhYIhdAAgEA8aAD2IBcAAIAAhNIhcAAgEA6VAD2IBdAAIAAhNIhdAAgEg+NgDYIAAkOIESAAIAAEOgEg7xgD2IBdAAIAAhYIhdAAgEg91gD2IBcAAIAAhYIhcAAgEg7xgF2IBdAAIAAhNIhdAAgEg91gF2IBcAAIAAhNIhcAAgEA58gDlIAAkOIESAAIAAEOgEA8agEDIBcAAIAAhXIhcAAgEA6VgEDIBdAAIAAhXIhdAAgEA8agGCIBcAAIAAhOIhcAAgEA6VgGCIBdAAIAAhOIhdAAgEg+NgMAIAAkOIESAAIAAEOgEg7xgMeIBdAAIAAhYIhdAAgEg91gMeIBcAAIAAhYIhcAAgEg7xgOeIBdAAIAAhNIhdAAgEg91gOeIBcAAIAAhNIhcAAgEA58gMNIAAkOIESAAIAAEOgEA8agMrIBcAAIAAhXIhcAAgEA6VgMrIBdAAIAAhXIhdAAgEA8agOqIBcAAIAAhOIhcAAgEA6VgOqIBdAAIAAhOIhdAAg");
	this.shape_81.setTransform(638.3,388.8);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#0E0E0E").s().p("Eg7xAP7IAAhXIBdAAIAABXgEg91AP7IAAhXIBcAAIAABXgEA8aAPvIAAhYIBcAAIAABYgEA6VAPvIAAhYIBdAAIAABYgEg7xAN8IAAhOIBdAAIAABOgEg91AN8IAAhOIBcAAIAABOgEA8aANvIAAhNIBcAAIAABNgEA6VANvIAAhNIBdAAIAABNgEg7xAGAIAAhYIBdAAIAABYgEg91AGAIAAhYIBcAAIAABYgEA8aAFzIAAhXIBcAAIAABXgEA6VAFzIAAhXIBdAAIAABXgEg7xAEAIAAhNIBdAAIAABNgEg91AEAIAAhNIBcAAIAABNgEA8aAD0IAAhOIBcAAIAABOgEA6VAD0IAAhOIBdAAIAABOgEg7xgD5IAAhXIBdAAIAABXgEg91gD5IAAhXIBcAAIAABXgEA8agEFIAAhYIBcAAIAABYgEA6VgEFIAAhYIBdAAIAABYgEg7xgF4IAAhOIBdAAIAABOgEg91gF4IAAhOIBcAAIAABOgEA8agGFIAAhNIBcAAIAABNgEA6VgGFIAAhNIBdAAIAABNgEg7xgMhIAAhXIBdAAIAABXgEg91gMhIAAhXIBcAAIAABXgEA8agMtIAAhYIBcAAIAABYgEA6VgMtIAAhYIBdAAIAABYgEg7xgOgIAAhOIBdAAIAABOgEg91gOgIAAhOIBcAAIAABOgEA8agOtIAAhNIBcAAIAABNgEA6VgOtIAAhNIBdAAIAABNg");
	this.shape_82.setTransform(638.3,389);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#7D8894").s().p("EhHFAX1MAAAgvcISmAAMAAAAvcgEg+pAN0IFKAAIAAlTIlKAAgEg+pAD4IFKAAIAAlRIlKAAgEg+pgGAIFKAAIAAlTIlKAAgEg+pgOoIFKAAIAAlTIlKAAgEA0gAXRMAAAgvFISmAAMAAAAvFgEA5gANnIFKAAIAAlTIlKAAgEA5gADsIFKAAIAAlRIlKAAgEA5ggGNIFKAAIAAlTIlKAAgEA5ggUIIAAFTIFKAAIAAlTIAAgBIlKAAg");
	this.shape_83.setTransform(638.3,409);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80}]}).wait(1));

	// back
	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#0E1215").s().p("ADWGuIAAtbIDfAAIAANbgAm1GuIAAtbIDNAAIAANbg");
	this.shape_84.setTransform(640.6,475);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#35424B").s().p("AsECIIAAkKIAAgGIYJAAIAAAGIAAEKg");
	this.shape_85.setTransform(640.4,538.9);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#263037").s().p("AsEAjIAAhFIFSAAIDMAAIG+AAIDgAAIFNAAIAABFg");
	this.shape_86.setTransform(640.4,521.6);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#13191D").s().p("AG4GuIAAtbIFNAAIAACJIAALSgAjmGuIAAtbIG+AAIAANbgAsEGuIAArSIAAiJIFSAAIAANbg");
	this.shape_87.setTransform(640.4,475);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84}]}).wait(1));

	// main
	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#BFBF36").s().p("EAviABxIAAjhIEJAAIAADhgEAzBABcIAIAAIARAAIABAAIAAgwIgBAAIgRAAIgIAAgEAyeABcIAGAAIANAAIAEAAIAAgwIgEAAIgNAAIgGAAgEAx3ABcIAJAAIAQAAIAAgwIgQAAIgJAAgEAw/ABcIAXAAIAAgwIgXAAgEAwcABcIAVAAIAAgwIgVAAgEAvzABcIAYAAIAAgwIgYAAgEAzBAAdIAIAAIARAAIABAAIAAgzIgBAAIgRAAIgIAAgEAyeAAdIAGAAIANAAIAEAAIAAgzIgEAAIgNAAIgGAAgEAx3AAdIAJAAIAQAAIAAgzIgQAAIgJAAgEAw/AAdIAXAAIAAgzIgXAAgEAwcAAdIAVAAIAAgzIgVAAgEAvzAAdIAYAAIAAgzIgYAAgEAzBgAmIAIAAIARAAIABAAIAAg1IgBAAIgRAAIgIAAgEAyegAmIAGAAIANAAIAEAAIAAg1IgEAAIgNAAIgGAAgEAx3gAmIAJAAIAQAAIAAg1IgQAAIgJAAgEAw/gAmIAXAAIAAg1IgXAAgEAwcgAmIAVAAIAAg1IgVAAgEAvzgAmIAYAAIAAg1IgYAAgEAmrABxIAAjhIEJAAIAADhgEAqKABcIAIAAIARAAIAAAAIAAgwIAAAAIgRAAIgIAAgEApnABcIAGAAIAMAAIAEAAIAAgwIgEAAIgMAAIgGAAgEApAABcIAIAAIAQAAIAAgwIgQAAIgIAAgEAoHABcIAYAAIAAgwIgYAAgEAnkABcIAWAAIAAgwIgWAAgEAm7ABcIAZAAIAAgwIgZAAgEAqKAAdIAIAAIARAAIAAAAIAAgzIAAAAIgRAAIgIAAgEApnAAdIAGAAIAMAAIAEAAIAAgzIgEAAIgMAAIgGAAgEApAAAdIAIAAIAQAAIAAgzIgQAAIgIAAgEAoHAAdIAYAAIAAgzIgYAAgEAnkAAdIAWAAIAAgzIgWAAgEAm7AAdIAZAAIAAgzIgZAAgEAqKgAmIAIAAIARAAIAAAAIAAg1IAAAAIgRAAIgIAAgEApngAmIAGAAIAMAAIAEAAIAAg1IgEAAIgMAAIgGAAgEApAgAmIAIAAIAQAAIAAg1IgQAAIgIAAgEAoHgAmIAYAAIAAg1IgYAAgEAnkgAmIAWAAIAAg1IgWAAgEAm7gAmIAZAAIAAg1IgZAAgAdMBxIAAjhIEIAAIAADhgEAgrABcIAIAAIAQAAIABAAIAAgwIgBAAIgQAAIgIAAgEAgIABcIAFAAIANAAIADAAIAAgwIgDAAIgNAAIgFAAgAfgBcIAIAAIAQAAIAAgwIgQAAIgIAAgAenBcIAZAAIAAgwIgZAAgAeEBcIAXAAIAAgwIgXAAgAdcBcIAYAAIAAgwIgYAAgEAgrAAdIAIAAIAQAAIABAAIAAgzIgBAAIgQAAIgIAAgEAgIAAdIAFAAIANAAIADAAIAAgzIgDAAIgNAAIgFAAgAfgAdIAIAAIAQAAIAAgzIgQAAIgIAAgAenAdIAZAAIAAgzIgZAAgAeEAdIAXAAIAAgzIgXAAgAdcAdIAYAAIAAgzIgYAAgEAgrgAmIAIAAIAQAAIABAAIAAg1IgBAAIgQAAIgIAAgEAgIgAmIAFAAIANAAIADAAIAAg1IgDAAIgNAAIgFAAgAfggmIAIAAIAQAAIAAg1IgQAAIgIAAgAengmIAZAAIAAg1IgZAAgAeEgmIAXAAIAAg1IgXAAgAdcgmIAYAAIAAg1IgYAAgASHBxIAAjhIEJAAIAADhgAVmBcIAIAAIARAAIABAAIAAgwIgBAAIgRAAIgIAAgAVDBcIAGAAIAMAAIAEAAIAAgwIgEAAIgMAAIgGAAgAUcBcIAIAAIAQAAIAAgwIgQAAIgIAAgATjBcIAYAAIAAgwIgYAAgATABcIAWAAIAAgwIgWAAgASYBcIAYAAIAAgwIgYAAgAVmAdIAIAAIARAAIABAAIAAgzIgBAAIgRAAIgIAAgAVDAdIAGAAIAMAAIAEAAIAAgzIgEAAIgMAAIgGAAgAUcAdIAIAAIAQAAIAAgzIgQAAIgIAAgATjAdIAYAAIAAgzIgYAAgATAAdIAWAAIAAgzIgWAAgASYAdIAYAAIAAgzIgYAAgAVmgmIAIAAIARAAIABAAIAAg1IgBAAIgRAAIgIAAgAVDgmIAGAAIAMAAIAEAAIAAg1IgEAAIgMAAIgGAAgAUcgmIAIAAIAQAAIAAg1IgQAAIgIAAgATjgmIAYAAIAAg1IgYAAgATAgmIAWAAIAAg1IgWAAgASYgmIAYAAIAAg1IgYAAgA1jBxIAAjhIEJAAIAADhgAyDBcIAIAAIAQAAIABAAIAAgwIgBAAIgQAAIgIAAgAymBcIAFAAIANAAIADAAIAAgwIgDAAIgNAAIgFAAgAzNBcIAHAAIAQAAIAAgwIgQAAIgHAAgA0HBcIAZAAIAAgwIgZAAgA0qBcIAXAAIAAgwIgXAAgA1SBcIAZAAIAAgwIgZAAgAyDAdIAIAAIAQAAIABAAIAAgzIgBAAIgQAAIgIAAgAymAdIAFAAIANAAIADAAIAAgzIgDAAIgNAAIgFAAgAzNAdIAHAAIAQAAIAAgzIgQAAIgHAAgA0HAdIAZAAIAAgzIgZAAgA0qAdIAXAAIAAgzIgXAAgA1SAdIAZAAIAAgzIgZAAgAyDgmIAIAAIAQAAIABAAIAAg1IgBAAIgQAAIgIAAgAymgmIAFAAIANAAIADAAIAAg1IgDAAIgNAAIgFAAgAzNgmIAHAAIAQAAIAAg1IgQAAIgHAAgA0HgmIAZAAIAAg1IgZAAgA0qgmIAXAAIAAg1IgXAAgA1SgmIAZAAIAAg1IgZAAgA/2BxIAAjhIEIAAIAADhgA8YBcIAIAAIARAAIABAAIAAgwIgBAAIgRAAIgIAAgA86BcIAFAAIANAAIADAAIAAgwIgDAAIgNAAIgFAAgA9iBcIAIAAIARAAIAAgwIgRAAIgIAAgA+aBcIAYAAIAAgwIgYAAgA+9BcIAVAAIAAgwIgVAAgA/mBcIAYAAIAAgwIgYAAgA8YAdIAIAAIARAAIABAAIAAgzIgBAAIgRAAIgIAAgA86AdIAFAAIANAAIADAAIAAgzIgDAAIgNAAIgFAAgA9iAdIAIAAIARAAIAAgzIgRAAIgIAAgA+aAdIAYAAIAAgzIgYAAgA+9AdIAVAAIAAgzIgVAAgA/mAdIAYAAIAAgzIgYAAgA8YgmIAIAAIARAAIABAAIAAg1IgBAAIgRAAIgIAAgA86gmIAFAAIANAAIADAAIAAg1IgDAAIgNAAIgFAAgA9igmIAIAAIARAAIAAg1IgRAAIgIAAgA+agmIAYAAIAAg1IgYAAgA+9gmIAVAAIAAg1IgVAAgA/mgmIAYAAIAAg1IgYAAgEgqZABxIAAjhIEIAAIAADhgEgm7ABcIAIAAIARAAIABAAIAAgwIgBAAIgRAAIgIAAgEgndABcIAFAAIANAAIADAAIAAgwIgDAAIgNAAIgFAAgEgoFABcIAIAAIARAAIAAgwIgRAAIgIAAgEgo9ABcIAYAAIAAgwIgYAAgEgpgABcIAVAAIAAgwIgVAAgEgqJABcIAYAAIAAgwIgYAAgEgm7AAdIAIAAIARAAIABAAIAAgzIgBAAIgRAAIgIAAgEgndAAdIAFAAIANAAIADAAIAAgzIgDAAIgNAAIgFAAgEgoFAAdIAIAAIARAAIAAgzIgRAAIgIAAgEgo9AAdIAYAAIAAgzIgYAAgEgpgAAdIAVAAIAAgzIgVAAgEgqJAAdIAYAAIAAgzIgYAAgEgm7gAmIAIAAIARAAIABAAIAAg1IgBAAIgRAAIgIAAgEgndgAmIAFAAIANAAIADAAIAAg1IgDAAIgNAAIgFAAgEgoFgAmIAIAAIARAAIAAg1IgRAAIgIAAgEgo9gAmIAYAAIAAg1IgYAAgEgpggAmIAVAAIAAg1IgVAAgEgqJgAmIAYAAIAAg1IgYAAgEgzqABxIAAjhIEIAAIAADhgEgwLABcIAIAAIAQAAIABAAIAAgwIgBAAIgQAAIgIAAgEgwuABcIAFAAIAOAAIADAAIAAgwIgDAAIgOAAIgFAAgEgxVABcIAIAAIAQAAIAAgwIgQAAIgIAAgEgyOABcIAYAAIAAgwIgYAAgEgyxABcIAWAAIAAgwIgWAAgEgzZABcIAYAAIAAgwIgYAAgEgwLAAdIAIAAIAQAAIABAAIAAgzIgBAAIgQAAIgIAAgEgwuAAdIAFAAIAOAAIADAAIAAgzIgDAAIgOAAIgFAAgEgxVAAdIAIAAIAQAAIAAgzIgQAAIgIAAgEgyOAAdIAYAAIAAgzIgYAAgEgyxAAdIAWAAIAAgzIgWAAgEgzZAAdIAYAAIAAgzIgYAAgEgwLgAmIAIAAIAQAAIABAAIAAg1IgBAAIgQAAIgIAAgEgwugAmIAFAAIAOAAIADAAIAAg1IgDAAIgOAAIgFAAgEgxVgAmIAIAAIAQAAIAAg1IgQAAIgIAAgEgyOgAmIAYAAIAAg1IgYAAgEgyxgAmIAWAAIAAg1IgWAAgEgzZgAmIAYAAIAAg1IgYAAg");
	this.shape_88.setTransform(636.2,489.5);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#394552").s().p("EAwyAIFIAAwJINyAAIAAQJgEAxYgA3IEJAAIAAjkIkJAAgEAnYAIFIAAwJIGUAAIAAQJgEAohgA3IEIAAIAAjkIkIAAgAcxIFIAAwJIHhAAIAAQJgAfBg3IEJAAIAAjkIkJAAgA0fIFIAAwFIKOAAIAAgEIDGAAIAAADIKHgBIAAgCIDGAAIAAABIA7AAIA6gBIR0AAIAAQJgAT9g3IEIAAIAAjkIkIAAgAztg3IEJAAIAAjkIkJAAgA/PIFIAAwFIHqAAIAAQFgA+Bg3IEJAAIAAjkIkJAAgEgp/AIFIAAwGIGNAAIBWAAIAFAAIACAAIAAQGgEgokgA3IEJAAIAAjkIkJAAgEg+jAIFIAAwIIGbAAIAPAAIANAAICpABIH+ABIAAQGgEgx0gA3IEIAAIAAjkIkIAAg");
	this.shape_89.setTransform(624.4,506.6);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#FEF8F6").s().p("EA9oAGgIjOAAIg7AAIilAAIg7AAIh9AAIg5AAIhiAAIg6AAIh8AAIg7AAIhsAAIg6AAIh0AAIg7AAIh1AAIg6AAIhgAAIg6AAIh+AAIg6AAIhfAAIg7AAIiBAAIg6AAIhgAAIg7AAIh9AAIg6AAIhhAAIg5AAIh8AAIg6AAIhgAAIg7AAIh8AAIg7AAIhhAAIg6AAIiBAAIg5AAIhhAAIg6AAIh9AAIg7AAIhdAAIg6AAIhqAAIg6AAIiEAAIg7AAIiJAAIg7AAIh0AAIg8AAIhfAAIg7AAIh9AAIg6AAIhtAAIg4AAIh2AAIg6AAIh+AAIg6AAIhgAAIg6AAIh9AAIg6AAIhtAAIg6AAIh2AAIg4AAIh1AAIg6AAIhgAAIg8AAIh8AAIg7AAIhgAAIg6AAIiAAAIg6AAIhhAAIg6AAIh+AAIg6AAIihAAIg6AAIiiAAIg6AAIAAgnIA6AAICiAAIA6AAIChAAIA6AAIB+AAIA6AAIBhAAIA6AAICAAAIA6AAIBgAAIA7AAIB8AAIA8AAIBgAAIA6AAIB1AAIA4AAIB2AAIA6AAIBtAAIA6AAIB9AAIA6AAIBgAAIA6AAIB+AAIA6AAIB2AAIA4AAIBtAAIA6AAIB9AAIA7AAIBfAAIA8AAIB0AAIA7AAICJAAIA7AAICEAAIA6AAIBqAAIA6AAIBdAAIA7AAIB9AAIA6AAIBhAAIA5AAICBAAIA6AAIBhAAIA7AAIB8AAIA7AAIBgAAIA6AAIB8AAIA5AAIBhAAIA6AAIB9AAIA7AAIBgAAIA6AAICBAAIA7AAIBfAAIA6AAIB+AAIA6AAIBgAAIA6AAIB1AAIA7AAIB0AAIA6AAIBsAAIA7AAIB8AAIA6AAIBiAAIA5AAIB9AAIA7AAIClAAIA7AAIDOAAIA8AAIAAAngEA9oAEGIjOAAIg7AAIilAAIg7AAIh9AAIg5AAIhiAAIg6AAIh8AAIg7AAIhsAAIg6AAIh0AAIg7AAIh1AAIg6AAIhgAAIg6AAIh+AAIg6AAIhfAAIg7AAIiBAAIg6AAIhgAAIg7AAIh9AAIg6AAIhhAAIg5AAIh8AAIg6AAIhgAAIg7AAIh8AAIg7AAIhhAAIg6AAIiBAAIg5AAIhhAAIg6AAIh9AAIg7AAIhdAAIg6AAIhqAAIg6AAIiEAAIg7AAIiJAAIg7AAIh0AAIg8AAIhfAAIg7AAIh9AAIg6AAIhtAAIg4AAIh2AAIg6AAIh+AAIg6AAIhgAAIg6AAIh9AAIg6AAIhtAAIg6AAIh2AAIg4AAIh1AAIg6AAIhgAAIg8AAIh8AAIg7AAIhgAAIg6AAIiAAAIg6AAIhhAAIg6AAIh+AAIg6AAIihAAIg6AAIiiAAIg6AAIAAgkIA6AAICiAAIA6AAIChAAIA6AAIB+AAIA6AAIBhAAIA6AAICAAAIA6AAIBgAAIA7AAIB8AAIA8AAIBgAAIA6AAIB1AAIA4AAIB2AAIA6AAIBtAAIA6AAIB9AAIA6AAIBgAAIA6AAIB+AAIA6AAIB2AAIA4AAIBtAAIA6AAIB9AAIA7AAIBfAAIA8AAIB0AAIA7AAICJAAIA7AAICEAAIA6AAIBqAAIA6AAIBdAAIA7AAIB9AAIA6AAIBhAAIA5AAICBAAIA6AAIBhAAIA7AAIB8AAIA7AAIBgAAIA6AAIB8AAIA5AAIBhAAIA6AAIB9AAIA7AAIBgAAIA6AAICBAAIA7AAIBfAAIA6AAIB+AAIA6AAIBgAAIA6AAIB1AAIA7AAIB0AAIA6AAIBsAAIA7AAIB8AAIA6AAIBiAAIA5AAIB9AAIA7AAIClAAIA7AAIDOAAIA8AAIAAAkgEA9oABbIjOAAIg7AAIilAAIg7AAIh9AAIg5AAIhiAAIg6AAIh8AAIg7AAIhsAAIg6AAIh0AAIg7AAIh1AAIg6AAIhgAAIg6AAIh+AAIg6AAIhfAAIg7AAIiBAAIg6AAIhgAAIg7AAIh9AAIg6AAIhhAAIg5AAIh8AAIg6AAIhgAAIg7AAIh8AAIg7AAIhhAAIg6AAIiBAAIg5AAIhhAAIg6AAIh9AAIg7AAIhdAAIg6AAIhqAAIg6AAIiEAAIg7AAIiJAAIg7AAIh0AAIg8AAIhfAAIg7AAIh9AAIg6AAIhtAAIg4AAIh2AAIg6AAIh+AAIg6AAIhgAAIg6AAIh9AAIg6AAIhtAAIg6AAIh2AAIg4AAIh1AAIg6AAIhgAAIg8AAIh8AAIg7AAIhgAAIg6AAIiAAAIg6AAIhhAAIg6AAIh+AAIg6AAIihAAIg6AAIiiAAIg6AAIAAgmIA6AAICiAAIA6AAIChAAIA6AAIB+AAIA6AAIBhAAIA6AAICAAAIA6AAIBgAAIA7AAIB8AAIA8AAIBgAAIA6AAIB1AAIA4AAIB2AAIA6AAIBtAAIA6AAIB9AAIA6AAIBgAAIA6AAIB+AAIA6AAIB2AAIA4AAIBtAAIA6AAIB9AAIA7AAIBfAAIA8AAIB0AAIA7AAICJAAIA7AAICEAAIA6AAIBqAAIA6AAIBdAAIA7AAIB9AAIA6AAIBhAAIA5AAICBAAIA6AAIBhAAIA7AAIB8AAIA7AAIBgAAIA6AAIB8AAIA5AAIBhAAIA6AAIB9AAIA7AAIBgAAIA6AAICBAAIA7AAIBfAAIA6AAIB+AAIA6AAIBgAAIA6AAIB1AAIA7AAIB0AAIA6AAIBsAAIA7AAIB8AAIA6AAIBiAAIA5AAIB9AAIA7AAIClAAIA7AAIDOAAIA8AAIAAAmgEA9ogDEIjOAAIg7AAIilAAIg7AAIh9AAIg5AAIhiAAIg6AAIh8AAIg7AAIhsAAIg6AAIh0AAIg7AAIh1AAIg6AAIhgAAIg6AAIh+AAIg6AAIhfAAIg7AAIiBAAIg6AAIhgAAIg7AAIh9AAIg6AAIhhAAIg5AAIh8AAIg6AAIhgAAIg7AAIh8AAIg7AAIhhAAIg6AAIiBAAIg5AAIhhAAIg6AAIh9AAIg7AAIhdAAIg6AAIhqAAIg6AAIiEAAIg7AAIiJAAIg7AAIh0AAIg8AAIhfAAIg7AAIh9AAIg6AAIhtAAIg4AAIh2AAIg6AAIh+AAIg6AAIhgAAIg6AAIh9AAIg6AAIhtAAIg6AAIh2AAIg4AAIh1AAIg6AAIhgAAIg8AAIh8AAIg7AAIhgAAIg6AAIiAAAIg6AAIhhAAIg6AAIh+AAIg6AAIihAAIg6AAIiiAAIg6AAIAAgoIA6AAICiAAIA6AAIChAAIA6AAIB+AAIA6AAIBhAAIA6AAICAAAIA6AAIBgAAIA7AAIB8AAIA8AAIBgAAIA6AAIB1AAIA4AAIB2AAIA6AAIBtAAIA6AAIB9AAIA6AAIBgAAIA6AAIB+AAIA6AAIB2AAIA4AAIBtAAIA6AAIB9AAIA7AAIBfAAIA8AAIB0AAIA7AAICJAAIA7AAICEAAIA6AAIBqAAIA6AAIBdAAIA7AAIB9AAIA6AAIBhAAIA5AAICBAAIA6AAIBhAAIA7AAIB8AAIA7AAIBgAAIA6AAIB8AAIA5AAIBhAAIA6AAIB9AAIA7AAIBgAAIA6AAICBAAIA7AAIBfAAIA6AAIB+AAIA6AAIBgAAIA6AAIB1AAIA7AAIB0AAIA6AAIBsAAIA7AAIB8AAIA6AAIBiAAIA5AAIB9AAIA7AAIClAAIA7AAIDOAAIA8AAIAAAogEA9ogF5IjOAAIg7AAIilAAIg7AAIh9AAIg5AAIhiAAIg6AAIh8AAIg7AAIhsAAIg6AAIh0AAIg7AAIh1AAIg6AAIhgAAIg6AAIh+AAIg6AAIhfAAIg7AAIiBAAIg6AAIhgAAIg7AAIh9AAIg6AAIhhAAIg5AAIh8AAIg6AAIhgAAIg7AAIh8AAIg7AAIhhAAIg6AAIiBAAIg5AAIhhAAIg6AAIh9AAIg7AAIhdAAIg6AAIhqAAIg6AAIiEAAIg7AAIiJAAIg7AAIh0AAIg8AAIhfAAIg7AAIh9AAIg6AAIhtAAIg4AAIh2AAIg6AAIh+AAIg6AAIhgAAIg6AAIh9AAIg6AAIhtAAIg6AAIh2AAIg4AAIh1AAIg6AAIhgAAIg8AAIh8AAIg7AAIhgAAIg6AAIiAAAIg6AAIhhAAIg6AAIh+AAIg6AAIihAAIg6AAIiiAAIg6AAIAAgmIA6AAICiAAIA6AAIChAAIA6AAIB+AAIA6AAIBhAAIA6AAICAAAIA6AAIBgAAIA7AAIB8AAIA8AAIBgAAIA6AAIB1AAIA4AAIB2AAIA6AAIBtAAIA6AAIB9AAIA6AAIBgAAIA6AAIB+AAIA6AAIB2AAIA4AAIBtAAIA6AAIB9AAIA7AAIBfAAIA8AAIB0AAIA7AAICJAAIA7AAICEAAIA6AAIBqAAIA6AAIBdAAIA7AAIB9AAIA6AAIBhAAIA5AAICBAAIA6AAIBhAAIA7AAIB8AAIA7AAIBgAAIA6AAIB8AAIA5AAIBhAAIA6AAIB9AAIA7AAIBgAAIA6AAICBAAIA7AAIBfAAIA6AAIB+AAIA6AAIBgAAIA6AAIB1AAIA7AAIB0AAIA6AAIBsAAIA7AAIB8AAIA6AAIBiAAIA5AAIB9AAIA7AAIClAAIA7AAIDOAAIA8AAIAAAmg");
	this.shape_90.setTransform(624.4,381.1);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#F1F165").s().p("Eg+jAKjIAAhiIA6AAICiAAIA6AAIChAAIA6AAIB+AAIA6AAIBhAAIA6AAICAAAIA6AAIBgAAIA7AAIB8AAIA8AAIBgAAIA6AAIB1AAIA4AAIB2AAIA6AAIBtAAIA6AAIB9AAIA6AAIBgAAIA6AAIB+AAIA6AAIB2AAIA4AAIBtAAIA6AAIB9AAIA7AAIBfAAIA8AAIB0AAIA7AAICJAAIA7AAICEAAIA6AAIBqAAIA6AAIBdAAIA7AAIB9AAIA6AAIBhAAIA5AAICBAAIA6AAIBhAAIA7AAIB8AAIA7AAIBgAAIA6AAIB8AAIA5AAIBhAAIA6AAIB9AAIA7AAIBgAAIA6AAICBAAIA7AAIBfAAIA6AAIB+AAIA6AAIBgAAIA6AAIB1AAIA7AAIB0AAIA6AAIBsAAIA7AAIB8AAIA6AAIBiAAIA5AAIB9AAIA7AAIClAAIA7AAIDOAAIA8AAIAABigEA6aABTIAAhuIDOAAIAABugEA26ABTIAAhuIClAAIAABugEA0CABTIAAhuIB9AAIAABugEAxnABTIAAhuIBiAAIAABugEAuxABTIAAhuIB8AAIAABugEAsKABTIAAhuIBsAAIAABugEApcABTIAAhuIB0AAIAABugEAmsABTIAAhuIB1AAIAABugEAkSABTIAAhuIBgAAIAABugEAhaABTIAAhuIB+AAIAABugAfBBTIAAhuIBfAAIAABugAcFBTIAAhuICBAAIAABugAZrBTIAAhuIBgAAIAABugAWzBTIAAhuIB9AAIAABugAUYBTIAAhuIBhAAIAABugARjBTIAAhuIB8AAIAABugAPJBTIAAhuIBgAAIAABugAMSBTIAAhuIB8AAIAABugAJ2BTIAAhuIBhAAIAABugAG7BTIAAhuICBAAIAABugAEhBTIAAhuIBhAAIAABugABqBTIAAhuIB9AAIAABugAguBTIAAhuIBdAAIAABugAjSBTIAAhuIBqAAIAABugAmQBTIAAhuICEAAIAABugApUBTIAAhuICJAAIAABugAsDBTIAAhuIB0AAIAABugAueBTIAAhuIBfAAIAABugAxWBTIAAhuIB9AAIAABugAz9BTIAAhuIBtAAIAABugA2rBTIAAhuIB2AAIAABugA5jBTIAAhuIB+AAIAABugA79BTIAAhuIBgAAIAABugA+0BTIAAhuIB9AAIAABugEghbABTIAAhuIBtAAIAABugEgkLABTIAAhuIB2AAIAABugEgm4ABTIAAhuIB1AAIAABugEgpSABTIAAhuIBgAAIAABugEgsKABTIAAhuIB8AAIAABugEgulABTIAAhuIBgAAIAABugEgxfABTIAAhuICAAAIAABugEgz6ABTIAAhuIBhAAIAABugEg2yABTIAAhuIB+AAIAABugEg6NABTIAAhuIChAAIAABugEg9pABTIAAhuICiAAIAABugEA9ogIzIjOAAIg7AAIilAAIg7AAIh9AAIg5AAIhiAAIg6AAIh8AAIg7AAIhsAAIg6AAIh0AAIg7AAIh1AAIg6AAIhgAAIg6AAIh+AAIg6AAIhfAAIg7AAIiBAAIg6AAIhgAAIg7AAIh9AAIg6AAIhhAAIg5AAIh8AAIg6AAIhgAAIg7AAIh8AAIg7AAIhhAAIg6AAIiBAAIg5AAIhhAAIg6AAIh9AAIg7AAIhdAAIg6AAIhqAAIg6AAIiEAAIg7AAIiJAAIg7AAIh0AAIg8AAIhfAAIg7AAIh9AAIg6AAIhtAAIg4AAIh2AAIg6AAIh+AAIg6AAIhgAAIg6AAIh9AAIg6AAIhtAAIg6AAIh2AAIg4AAIh1AAIg6AAIhgAAIg8AAIh8AAIg7AAIhgAAIg6AAIiAAAIg6AAIhhAAIg6AAIh+AAIg6AAIihAAIg6AAIiiAAIg6AAIAAhvMB9HAAAIAABvg");
	this.shape_91.setTransform(624.4,378.1);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#7D8894").s().p("EAr2AIFIAAwJIDGAAIAAQJgEAicAIFIAAwJIDGAAIAAQJgAX1IFIAAwJIDGAAIAAQJgA5bIFIAAwFIAAgEIDGAAIAAAEIAAQFgEgkLAIFIAAwGIAAgDIDGAAIAAAEIAAQFgEgu7AIFIAAwGIAAgDIDGAAIAAADIAAQGg");
	this.shape_92.setTransform(636.2,506.6);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#D03F33").s().p("A0fKXIjGAAIAAAEInqAAIAAgEIjGAAIAAADIgCAAIgFAAIhWAAImNAAIAAgDIjGAAIAAADIn+gBIipgBIgNAAIgPAAImbAAIAAhcMB9HAAAIAABbItyAAIjGAAImUAAIjGAAInhAAIjGAAIx0AAIg6ABIg7AAIAAgBIjGAAIAAACIqHABIAAgDIjGAAIAAAEIqOAAgEA9oAHaIAAiDIA8AAIAACDgEA5fAHaIAAiDIA7AAIAACDgEA1/AHaIAAiDIA7AAIAACDgEAzJAHaIAAiDIA5AAIAACDgEAwtAHaIAAiDIA6AAIAACDgEAt2AHaIAAiDIA7AAIAACDgEArQAHaIAAiDIA6AAIAACDgEAohAHaIAAiDIA7AAIAACDgEAlyAHaIAAiDIA6AAIAACDgEAjYAHaIAAiDIA6AAIAACDgEAggAHaIAAiDIA6AAIAACDgAeGHaIAAiDIA7AAIAACDgAbLHaIAAiDIA6AAIAACDgAYwHaIAAiDIA7AAIAACDgAV5HaIAAiDIA6AAIAACDgATfHaIAAiDIA5AAIAACDgAQpHaIAAiDIA6AAIAACDgAOOHaIAAiDIA7AAIAACDgALXHaIAAiDIA7AAIAACDgAI8HaIAAiDIA6AAIAACDgAGCHaIAAiDIA5AAIAACDgADnHaIAAiDIA6AAIAACDgAAvHaIAAiDIA7AAIAACDgAhoHaIAAiDIA6AAIAACDgAkMHaIAAiDIA6AAIAACDgAnLHaIAAiDIA7AAIAACDgAqPHaIAAiDIA7AAIAACDgAs/HaIAAiDIA8AAIAACDgAvZHaIAAiDIA7AAIAACDgAyQHaIAAiDIA6AAIAACDgA01HaIAAiDIA4AAIAACDgA3lHaIAAiDIA6AAIAACDgA6dHaIAAiDIA6AAIAACDgA83HaIAAiDIA6AAIAACDgA/uHaIAAiDIA6AAIAACDgEgiVAHaIAAiDIA6AAIAACDgEglDAHaIAAiDIA4AAIAACDgEgnyAHaIAAiDIA6AAIAACDgEgqOAHaIAAiDIA8AAIAACDgEgtFAHaIAAiDIA7AAIAACDgEgvfAHaIAAiDIA6AAIAACDgEgyZAHaIAAiDIA6AAIAACDgEg00AHaIAAiDIA6AAIAACDgEg3sAHaIAAiDIA6AAIAACDgEg7HAHaIAAiDIA6AAIAACDgEg+jAHaIAAiDIA6AAIAACDgEA9oAEwIAAhzIA8AAIAABzgEA5fAEwIAAhzIA7AAIAABzgEA1/AEwIAAhzIA7AAIAABzgEAzJAEwIAAhzIA5AAIAABzgEAwtAEwIAAhzIA6AAIAABzgEAt2AEwIAAhzIA7AAIAABzgEArQAEwIAAhzIA6AAIAABzgEAohAEwIAAhzIA7AAIAABzgEAlyAEwIAAhzIA6AAIAABzgEAjYAEwIAAhzIA6AAIAABzgEAggAEwIAAhzIA6AAIAABzgAeGEwIAAhzIA7AAIAABzgAbLEwIAAhzIA6AAIAABzgAYwEwIAAhzIA7AAIAABzgAV5EwIAAhzIA6AAIAABzgATfEwIAAhzIA5AAIAABzgAQpEwIAAhzIA6AAIAABzgAOOEwIAAhzIA7AAIAABzgALXEwIAAhzIA7AAIAABzgAI8EwIAAhzIA6AAIAABzgAGCEwIAAhzIA5AAIAABzgADnEwIAAhzIA6AAIAABzgAAvEwIAAhzIA7AAIAABzgAhoEwIAAhzIA6AAIAABzgAkMEwIAAhzIA6AAIAABzgAnLEwIAAhzIA7AAIAABzgAqPEwIAAhzIA7AAIAABzgAs/EwIAAhzIA8AAIAABzgAvZEwIAAhzIA7AAIAABzgAyQEwIAAhzIA6AAIAABzgA01EwIAAhzIA4AAIAABzgA3lEwIAAhzIA6AAIAABzgA6dEwIAAhzIA6AAIAABzgA83EwIAAhzIA6AAIAABzgA/uEwIAAhzIA6AAIAABzgEgiVAEwIAAhzIA6AAIAABzgEglDAEwIAAhzIA4AAIAABzgEgnyAEwIAAhzIA6AAIAABzgEgqOAEwIAAhzIA8AAIAABzgEgtFAEwIAAhzIA7AAIAABzgEgvfAEwIAAhzIA6AAIAABzgEgyZAEwIAAhzIA6AAIAABzgEg00AEwIAAhzIA6AAIAABzgEg3sAEwIAAhzIA6AAIAABzgEg7HAEwIAAhzIA6AAIAABzgEg+jAEwIAAhzIA6AAIAABzgEA9oACYIAAiGIA8AAIAACGgEA5fACYIAAiGIA7AAIAACGgEA1/ACYIAAiGIA7AAIAACGgEAzJACYIAAiGIA5AAIAACGgEAwtACYIAAiGIA6AAIAACGgEAt2ACYIAAiGIA7AAIAACGgEArQACYIAAiGIA6AAIAACGgEAohACYIAAiGIA7AAIAACGgEAlyACYIAAiGIA6AAIAACGgEAjYACYIAAiGIA6AAIAACGgEAggACYIAAiGIA6AAIAACGgAeGCYIAAiGIA7AAIAACGgAbLCYIAAiGIA6AAIAACGgAYwCYIAAiGIA7AAIAACGgAV5CYIAAiGIA6AAIAACGgATfCYIAAiGIA5AAIAACGgAQpCYIAAiGIA6AAIAACGgAOOCYIAAiGIA7AAIAACGgALXCYIAAiGIA7AAIAACGgAI8CYIAAiGIA6AAIAACGgAGCCYIAAiGIA5AAIAACGgADnCYIAAiGIA6AAIAACGgAAvCYIAAiGIA7AAIAACGgAhoCYIAAiGIA6AAIAACGgAkMCYIAAiGIA6AAIAACGgAnLCYIAAiGIA7AAIAACGgAqPCYIAAiGIA7AAIAACGgAs/CYIAAiGIA8AAIAACGgAvZCYIAAiGIA7AAIAACGgAyQCYIAAiGIA6AAIAACGgA01CYIAAiGIA4AAIAACGgA3lCYIAAiGIA6AAIAACGgA6dCYIAAiGIA6AAIAACGgA83CYIAAiGIA6AAIAACGgA/uCYIAAiGIA6AAIAACGgEgiVACYIAAiGIA6AAIAACGgEglDACYIAAiGIA4AAIAACGgEgnyACYIAAiGIA6AAIAACGgEgqOACYIAAiGIA8AAIAACGgEgtFACYIAAiGIA7AAIAACGgEgvfACYIAAiGIA6AAIAACGgEgyZACYIAAiGIA6AAIAACGgEg00ACYIAAiGIA6AAIAACGgEg3sACYIAAiGIA6AAIAACGgEg7HACYIAAiGIA6AAIAACGgEg+jACYIAAiGIA6AAIAACGgEA9ogASIAAhwIAAiLIA8AAIAACLIAABwgEA5fgASIAAhwIAAiLIA7AAIAACLIAABwgEA1/gASIAAhwIAAiLIA7AAIAACLIAABwgEAzJgASIAAhwIAAiLIA5AAIAACLIAABwgEAwtgASIAAhwIAAiLIA6AAIAACLIAABwgEAt2gASIAAhwIAAiLIA7AAIAACLIAABwgEArQgASIAAhwIAAiLIA6AAIAACLIAABwgEAohgASIAAhwIAAiLIA7AAIAACLIAABwgEAlygASIAAhwIAAiLIA6AAIAACLIAABwgEAjYgASIAAhwIAAiLIA6AAIAACLIAABwgEAgggASIAAhwIAAiLIA6AAIAACLIAABwgAeGgSIAAhwIAAiLIA7AAIAACLIAABwgAbLgSIAAhwIAAiLIA6AAIAACLIAABwgAYwgSIAAhwIAAiLIA7AAIAACLIAABwgAV5gSIAAhwIAAiLIA6AAIAACLIAABwgATfgSIAAhwIAAiLIA5AAIAACLIAABwgAQpgSIAAhwIAAiLIA6AAIAACLIAABwgAOOgSIAAhwIAAiLIA7AAIAACLIAABwgALXgSIAAhwIAAiLIA7AAIAACLIAABwgAI8gSIAAhwIAAiLIA6AAIAACLIAABwgAGCgSIAAhwIAAiLIA5AAIAACLIAABwgADngSIAAhwIAAiLIA6AAIAACLIAABwgAAvgSIAAhwIAAiLIA7AAIAACLIAABwgAhogSIAAhwIAAiLIA6AAIAACLIAABwgAkMgSIAAhwIAAiLIA6AAIAACLIAABwgAnLgSIAAhwIAAiLIA7AAIAACLIAABwgAqPgSIAAhwIAAiLIA7AAIAACLIAABwgAs/gSIAAhwIAAiLIA8AAIAACLIAABwgAvZgSIAAhwIAAiLIA7AAIAACLIAABwgAyQgSIAAhwIAAiLIA6AAIAACLIAABwgA01gSIAAhwIAAiLIA4AAIAACLIAABwgA3lgSIAAhwIAAiLIA6AAIAACLIAABwgA6dgSIAAhwIAAiLIA6AAIAACLIAABwgA83gSIAAhwIAAiLIA6AAIAACLIAABwgA/ugSIAAhwIAAiLIA6AAIAACLIAABwgEgiVgASIAAhwIAAiLIA6AAIAACLIAABwgEglDgASIAAhwIAAiLIA4AAIAACLIAABwgEgnygASIAAhwIAAiLIA6AAIAACLIAABwgEgqOgASIAAhwIAAiLIA8AAIAACLIAABwgEgtFgASIAAhwIAAiLIA7AAIAACLIAABwgEgvfgASIAAhwIAAiLIA6AAIAACLIAABwgEgyZgASIAAhwIAAiLIA6AAIAACLIAABwgEg00gASIAAhwIAAiLIA6AAIAACLIAABwgEg3sgASIAAhwIAAiLIA6AAIAACLIAABwgEg7HgASIAAhwIAAiLIA6AAIAACLIAABwgEg+jgASIAAhwIAAiLIA6AAIAACLIAABwgEA9ogE1IAAiNIA8AAIAACNgEA5fgE1IAAiNIA7AAIAACNgEA1/gE1IAAiNIA7AAIAACNgEAzJgE1IAAiNIA5AAIAACNgEAwtgE1IAAiNIA6AAIAACNgEAt2gE1IAAiNIA7AAIAACNgEArQgE1IAAiNIA6AAIAACNgEAohgE1IAAiNIA7AAIAACNgEAlygE1IAAiNIA6AAIAACNgEAjYgE1IAAiNIA6AAIAACNgEAgggE1IAAiNIA6AAIAACNgAeGk1IAAiNIA7AAIAACNgAbLk1IAAiNIA6AAIAACNgAYwk1IAAiNIA7AAIAACNgAV5k1IAAiNIA6AAIAACNgATfk1IAAiNIA5AAIAACNgAQpk1IAAiNIA6AAIAACNgAOOk1IAAiNIA7AAIAACNgALXk1IAAiNIA7AAIAACNgAI8k1IAAiNIA6AAIAACNgAGCk1IAAiNIA5AAIAACNgADnk1IAAiNIA6AAIAACNgAAvk1IAAiNIA7AAIAACNgAhok1IAAiNIA6AAIAACNgAkMk1IAAiNIA6AAIAACNgAnLk1IAAiNIA7AAIAACNgAqPk1IAAiNIA7AAIAACNgAs/k1IAAiNIA8AAIAACNgAvZk1IAAiNIA7AAIAACNgAyQk1IAAiNIA6AAIAACNgA01k1IAAiNIA4AAIAACNgA3lk1IAAiNIA6AAIAACNgA6dk1IAAiNIA6AAIAACNgA83k1IAAiNIA6AAIAACNgA/uk1IAAiNIA6AAIAACNgEgiVgE1IAAiNIA6AAIAACNgEglDgE1IAAiNIA4AAIAACNgEgnygE1IAAiNIA6AAIAACNgEgqOgE1IAAiNIA8AAIAACNgEgtFgE1IAAiNIA7AAIAACNgEgvfgE1IAAiNIA6AAIAACNgEgyZgE1IAAiNIA6AAIAACNgEg00gE1IAAiNIA6AAIAACNgEg3sgE1IAAiNIA6AAIAACNgEg7HgE1IAAiNIA6AAIAACNgEg+jgE1IAAiNIA6AAIAACNgEA9ogHoIAAiyIA8AAIAACygEA5fgHoIAAiyIA7AAIAACygEA1/gHoIAAiyIA7AAIAACygEAzJgHoIAAiyIA5AAIAACygEAwtgHoIAAiyIA6AAIAACygEAt2gHoIAAiyIA7AAIAACygEArQgHoIAAiyIA6AAIAACygEAohgHoIAAiyIA7AAIAACygEAlygHoIAAiyIA6AAIAACygEAjYgHoIAAiyIA6AAIAACygEAgggHoIAAiyIA6AAIAACygAeGnoIAAiyIA7AAIAACygAbLnoIAAiyIA6AAIAACygAYwnoIAAiyIA7AAIAACygAV5noIAAiyIA6AAIAACygATfnoIAAiyIA5AAIAACygAQpnoIAAiyIA6AAIAACygAOOnoIAAiyIA7AAIAACygALXnoIAAiyIA7AAIAACygAI8noIAAiyIA6AAIAACygAGCnoIAAiyIA5AAIAACygADnnoIAAiyIA6AAIAACygAAvnoIAAiyIA7AAIAACygAhonoIAAiyIA6AAIAACygAkMnoIAAiyIA6AAIAACygAnLnoIAAiyIA7AAIAACygAqPnoIAAiyIA7AAIAACygAs/noIAAiyIA8AAIAACygAvZnoIAAiyIA7AAIAACygAyQnoIAAiyIA6AAIAACygA01noIAAiyIA4AAIAACygA3lnoIAAiyIA6AAIAACygA6dnoIAAiyIA6AAIAACygA83noIAAiyIA6AAIAACygA/unoIAAiyIA6AAIAACygEgiVgHoIAAiyIA6AAIAACygEglDgHoIAAiyIA4AAIAACygEgnygHoIAAiyIA6AAIAACygEgqOgHoIAAiyIA8AAIAACygEgtFgHoIAAiyIA7AAIAACygEgvfgHoIAAiyIA6AAIAACygEgyZgHoIAAiyIA6AAIAACygEg00gHoIAAiyIA6AAIAACygEg3sgHoIAAiyIA6AAIAACygEg7HgHoIAAiyIA6AAIAACygEg+jgHoIAAiyIA6AAIAACyg");
	this.shape_93.setTransform(624.4,388.5);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#0E0E0E").s().p("EA1QAN1IgQAAIgIAAIAAgwIAIAAIAQAAIACAAIAAAwgEA0oAN1IgOAAIgFAAIAAgwIAFAAIAOAAIADAAIAAAwgEAz2AN1IgIAAIAAgwIAIAAIAQAAIAAAwgEAy1AN1IAAgwIAYAAIAAAwgEAySAN1IAAgwIAWAAIAAAwgEAxqAN1IAAgwIAYAAIAAAwgEAsZAN1IgQAAIgIAAIAAgwIAIAAIAQAAIABAAIAAAwgEArwAN1IgNAAIgFAAIAAgwIAFAAIANAAIADAAIAAAwgEAq+AN1IgIAAIAAgwIAIAAIAQAAIAAAwgEAp9AN1IAAgwIAZAAIAAAwgEApaAN1IAAgwIAXAAIAAAwgEAoyAN1IAAgwIAYAAIAAAwgEAi6AN1IgRAAIgIAAIAAgwIAIAAIARAAIAAAAIAAAwgEAiQAN1IgMAAIgGAAIAAgwIAGAAIAMAAIAEAAIAAAwgEAhfAN1IgIAAIAAgwIAIAAIAQAAIAAAwgEAgeAN1IAAgwIAYAAIAAAwgAf7N1IAAgwIAWAAIAAAwgAfSN1IAAgwIAZAAIAAAwgAX1N1IgRAAIgIAAIAAgwIAIAAIARAAIABAAIAAAwgAXMN1IgNAAIgFAAIAAgwIAFAAIANAAIADAAIAAAwgAWaN1IgIAAIAAgwIAIAAIARAAIAAAwgAVaN1IAAgwIAYAAIAAAwgAU2N1IAAgwIAWAAIAAAwgAUON1IAAgwIAYAAIAAAwgAv1N1IgQAAIgIAAIAAgwIAIAAIAQAAIABAAIAAAwgAweN1IgMAAIgGAAIAAgwIAGAAIAMAAIAEAAIAAAwgAxPN1IgIAAIAAgwIAIAAIAQAAIAAAwgAyQN1IAAgwIAYAAIAAAwgAyzN1IAAgwIAWAAIAAAwgAzcN1IAAgwIAZAAIAAAwgA6IN1IgRAAIgIAAIAAgwIAIAAIARAAIABAAIAAAwgA6yN1IgMAAIgGAAIAAgwIAGAAIAMAAIAEAAIAAAwgA7jN1IgIAAIAAgwIAIAAIAQAAIAAAwgA8kN1IAAgwIAYAAIAAAwgA9HN1IAAgwIAWAAIAAAwgA9wN1IAAgwIAZAAIAAAwgEgkrAN1IgRAAIgIAAIAAgwIAIAAIARAAIABAAIAAAwgEglVAN1IgMAAIgGAAIAAgwIAGAAIAMAAIAEAAIAAAwgEgmGAN1IgIAAIAAgwIAIAAIAQAAIAAAwgEgnHAN1IAAgwIAYAAIAAAwgEgnqAN1IAAgwIAWAAIAAAwgEgoTAN1IAAgwIAZAAIAAAwgEgt8AN1IgQAAIgJAAIAAgwIAJAAIAQAAIABAAIAAAwgEgulAN1IgNAAIgGAAIAAgwIAGAAIANAAIAEAAIAAAwgEgvWAN1IgIAAIAAgwIAIAAIAQAAIAAAwgEgwXAN1IAAgwIAXAAIAAAwgEgw6AN1IAAgwIAVAAIAAAwgEgxjAN1IAAgwIAZAAIAAAwgEA1QAM2IgQAAIgIAAIAAg1IAIAAIAQAAIACAAIAAA1gEA0oAM2IgOAAIgFAAIAAg1IAFAAIAOAAIADAAIAAA1gEAz2AM2IgIAAIAAg1IAIAAIAQAAIAAA1gEAy1AM2IAAg1IAYAAIAAA1gEAySAM2IAAg1IAWAAIAAA1gEAxqAM2IAAg1IAYAAIAAA1gEAsZAM2IgQAAIgIAAIAAg1IAIAAIAQAAIABAAIAAA1gEArwAM2IgNAAIgFAAIAAg1IAFAAIANAAIADAAIAAA1gEAq+AM2IgIAAIAAg1IAIAAIAQAAIAAA1gEAp9AM2IAAg1IAZAAIAAA1gEApaAM2IAAg1IAXAAIAAA1gEAoyAM2IAAg1IAYAAIAAA1gEAi6AM2IgRAAIgIAAIAAg1IAIAAIARAAIAAAAIAAA1gEAiQAM2IgMAAIgGAAIAAg1IAGAAIAMAAIAEAAIAAA1gEAhfAM2IgIAAIAAg1IAIAAIAQAAIAAA1gEAgeAM2IAAg1IAYAAIAAA1gAf7M2IAAg1IAWAAIAAA1gAfSM2IAAg1IAZAAIAAA1gAX1M2IgRAAIgIAAIAAg1IAIAAIARAAIABAAIAAA1gAXMM2IgNAAIgFAAIAAg1IAFAAIANAAIADAAIAAA1gAWaM2IgIAAIAAg1IAIAAIARAAIAAA1gAVaM2IAAg1IAYAAIAAA1gAU2M2IAAg1IAWAAIAAA1gAUOM2IAAg1IAYAAIAAA1gAv1M2IgQAAIgIAAIAAg1IAIAAIAQAAIABAAIAAA1gAweM2IgMAAIgGAAIAAg1IAGAAIAMAAIAEAAIAAA1gAxPM2IgIAAIAAg1IAIAAIAQAAIAAA1gAyQM2IAAg1IAYAAIAAA1gAyzM2IAAg1IAWAAIAAA1gAzcM2IAAg1IAZAAIAAA1gA6IM2IgRAAIgIAAIAAg1IAIAAIARAAIABAAIAAA1gA6yM2IgMAAIgGAAIAAg1IAGAAIAMAAIAEAAIAAA1gA7jM2IgIAAIAAg1IAIAAIAQAAIAAA1gA8kM2IAAg1IAYAAIAAA1gA9HM2IAAg1IAWAAIAAA1gA9wM2IAAg1IAZAAIAAA1gEgkrAM2IgRAAIgIAAIAAg1IAIAAIARAAIABAAIAAA1gEglVAM2IgMAAIgGAAIAAg1IAGAAIAMAAIAEAAIAAA1gEgmGAM2IgIAAIAAg1IAIAAIAQAAIAAA1gEgnHAM2IAAg1IAYAAIAAA1gEgnqAM2IAAg1IAWAAIAAA1gEgoTAM2IAAg1IAZAAIAAA1gEgt8AM2IgQAAIgJAAIAAg1IAJAAIAQAAIABAAIAAA1gEgulAM2IgNAAIgGAAIAAg1IAGAAIANAAIAEAAIAAA1gEgvWAM2IgIAAIAAg1IAIAAIAQAAIAAA1gEgwXAM2IAAg1IAXAAIAAA1gEgw6AM2IAAg1IAVAAIAAA1gEgxjAM2IAAg1IAZAAIAAA1gEA1QALxIgQAAIgIAAIAAg1IAIAAIAQAAIACAAIAAA1gEA0oALxIgOAAIgFAAIAAg1IAFAAIAOAAIADAAIAAA1gEAz2ALxIgIAAIAAg1IAIAAIAQAAIAAA1gEAy1ALxIAAg1IAYAAIAAA1gEAySALxIAAg1IAWAAIAAA1gEAxqALxIAAg1IAYAAIAAA1gEAsZALxIgQAAIgIAAIAAg1IAIAAIAQAAIABAAIAAA1gEArwALxIgNAAIgFAAIAAg1IAFAAIANAAIADAAIAAA1gEAq+ALxIgIAAIAAg1IAIAAIAQAAIAAA1gEAp9ALxIAAg1IAZAAIAAA1gEApaALxIAAg1IAXAAIAAA1gEAoyALxIAAg1IAYAAIAAA1gEAi6ALxIgRAAIgIAAIAAg1IAIAAIARAAIAAAAIAAA1gEAiQALxIgMAAIgGAAIAAg1IAGAAIAMAAIAEAAIAAA1gEAhfALxIgIAAIAAg1IAIAAIAQAAIAAA1gEAgeALxIAAg1IAYAAIAAA1gAf7LxIAAg1IAWAAIAAA1gAfSLxIAAg1IAZAAIAAA1gAX1LxIgRAAIgIAAIAAg1IAIAAIARAAIABAAIAAA1gAXMLxIgNAAIgFAAIAAg1IAFAAIANAAIADAAIAAA1gAWaLxIgIAAIAAg1IAIAAIARAAIAAA1gAVaLxIAAg1IAYAAIAAA1gAU2LxIAAg1IAWAAIAAA1gAUOLxIAAg1IAYAAIAAA1gAv1LxIgQAAIgIAAIAAg1IAIAAIAQAAIABAAIAAA1gAweLxIgMAAIgGAAIAAg1IAGAAIAMAAIAEAAIAAA1gAxPLxIgIAAIAAg1IAIAAIAQAAIAAA1gAyQLxIAAg1IAYAAIAAA1gAyzLxIAAg1IAWAAIAAA1gAzcLxIAAg1IAZAAIAAA1gA6ILxIgRAAIgIAAIAAg1IAIAAIARAAIABAAIAAA1gA6yLxIgMAAIgGAAIAAg1IAGAAIAMAAIAEAAIAAA1gA7jLxIgIAAIAAg1IAIAAIAQAAIAAA1gA8kLxIAAg1IAYAAIAAA1gA9HLxIAAg1IAWAAIAAA1gA9wLxIAAg1IAZAAIAAA1gEgkrALxIgRAAIgIAAIAAg1IAIAAIARAAIABAAIAAA1gEglVALxIgMAAIgGAAIAAg1IAGAAIAMAAIAEAAIAAA1gEgmGALxIgIAAIAAg1IAIAAIAQAAIAAA1gEgnHALxIAAg1IAYAAIAAA1gEgnqALxIAAg1IAWAAIAAA1gEgoTALxIAAg1IAZAAIAAA1gEgt8ALxIgQAAIgJAAIAAg1IAJAAIAQAAIABAAIAAA1gEgulALxIgNAAIgGAAIAAg1IAGAAIANAAIAEAAIAAA1gEgvWALxIgIAAIAAg1IAIAAIAQAAIAAA1gEgwXALxIAAg1IAXAAIAAA1gEgw6ALxIAAg1IAVAAIAAA1gEgxjALxIAAg1IAZAAIAAA1gEA6bAEAIAAiDIDOAAIAACDgEA27AEAIAAiDIClAAIAACDgEA0DAEAIAAiDIB9AAIAACDgEAxoAEAIAAiDIBhAAIAACDgEAuxAEAIAAiDIB9AAIAACDgEAsLAEAIAAiDIBsAAIAACDgEApcAEAIAAiDIB0AAIAACDgEAmtAEAIAAiDIB1AAIAACDgEAkTAEAIAAiDIBfAAIAACDgEAhaAEAIAAiDIB/AAIAACDgAfCEAIAAiDIBfAAIAACDgAcGEAIAAiDICBAAIAACDgAZsEAIAAiDIBfAAIAACDgAW0EAIAAiDIB9AAIAACDgAUZEAIAAiDIBgAAIAACDgARkEAIAAiDIB7AAIAACDgAPKEAIAAiDIBfAAIAACDgAMSEAIAAiDIB9AAIAACDgAJ3EAIAAiDIBhAAIAACDgAG8EAIAAiDICBAAIAACDgAEiEAIAAiDIBhAAIAACDgABrEAIAAiDIB8AAIAACDgAguEAIAAiDIBeAAIAACDgAjSEAIAAiDIBqAAIAACDgAmQEAIAAiDICFAAIAACDgApTEAIAAiDICJAAIAACDgAsCEAIAAiDIB0AAIAACDgAudEAIAAiDIBfAAIAACDgAxVEAIAAiDIB9AAIAACDgAz8EAIAAiDIBtAAIAACDgA2rEAIAAiDIB2AAIAACDgA5iEAIAAiDIB+AAIAACDgA78EAIAAiDIBgAAIAACDgA+zEAIAAiDIB9AAIAACDgEghaAEAIAAiDIBsAAIAACDgEgkKAEAIAAiDIB2AAIAACDgEgm4AEAIAAiDIB1AAIAACDgEgpRAEAIAAiDIBgAAIAACDgEgsJAEAIAAiDIB8AAIAACDgEgulAEAIAAiDIBgAAIAACDgEgxeAEAIAAiDICAAAIAACDgEgz6AEAIAAiDIBiAAIAACDgEg2xAEAIAAiDIB9AAIAACDgEg6MAEAIAAiDIChAAIAACDgEg9oAEAIAAiDIChAAIAACDgEA6bABWIAAhxIDOAAIAABxgEA27ABWIAAhxIClAAIAABxgEA0DABWIAAhxIB9AAIAABxgEAxoABWIAAhxIBhAAIAABxgEAuxABWIAAhxIB9AAIAABxgEAsLABWIAAhxIBsAAIAABxgEApcABWIAAhxIB0AAIAABxgEAmtABWIAAhxIB1AAIAABxgEAkTABWIAAhxIBfAAIAABxgEAhaABWIAAhxIB/AAIAABxgAfCBWIAAhxIBfAAIAABxgAcGBWIAAhxICBAAIAABxgAZsBWIAAhxIBfAAIAABxgAW0BWIAAhxIB9AAIAABxgAUZBWIAAhxIBgAAIAABxgARkBWIAAhxIB7AAIAABxgAPKBWIAAhxIBfAAIAABxgAMSBWIAAhxIB9AAIAABxgAJ3BWIAAhxIBhAAIAABxgAG8BWIAAhxICBAAIAABxgAEiBWIAAhxIBhAAIAABxgABrBWIAAhxIB8AAIAABxgAguBWIAAhxIBeAAIAABxgAjSBWIAAhxIBqAAIAABxgAmQBWIAAhxICFAAIAABxgApTBWIAAhxICJAAIAABxgAsCBWIAAhxIB0AAIAABxgAudBWIAAhxIBfAAIAABxgAxVBWIAAhxIB9AAIAABxgAz8BWIAAhxIBtAAIAABxgA2rBWIAAhxIB2AAIAABxgA5iBWIAAhxIB+AAIAABxgA78BWIAAhxIBgAAIAABxgA+zBWIAAhxIB9AAIAABxgEghaABWIAAhxIBsAAIAABxgEgkKABWIAAhxIB2AAIAABxgEgm4ABWIAAhxIB1AAIAABxgEgpRABWIAAhxIBgAAIAABxgEgsJABWIAAhxIB8AAIAABxgEgulABWIAAhxIBgAAIAABxgEgxeABWIAAhxICAAAIAABxgEgz6ABWIAAhxIBiAAIAABxgEg2xABWIAAhxIB9AAIAABxgEg6MABWIAAhxIChAAIAABxgEg9oABWIAAhxIChAAIAABxgEA6bgA/IAAiHIDOAAIAACHgEA27gA/IAAiHIClAAIAACHgEA0DgA/IAAiHIB9AAIAACHgEAxogA/IAAiHIBhAAIAACHgEAuxgA/IAAiHIB9AAIAACHgEAsLgA/IAAiHIBsAAIAACHgEApcgA/IAAiHIB0AAIAACHgEAmtgA/IAAiHIB1AAIAACHgEAkTgA/IAAiHIBfAAIAACHgEAhagA/IAAiHIB/AAIAACHgAfCg/IAAiHIBfAAIAACHgAcGg/IAAiHICBAAIAACHgAZsg/IAAiHIBfAAIAACHgAW0g/IAAiHIB9AAIAACHgAUZg/IAAiHIBgAAIAACHgARkg/IAAiHIB7AAIAACHgAPKg/IAAiHIBfAAIAACHgAMSg/IAAiHIB9AAIAACHgAJ3g/IAAiHIBhAAIAACHgAG8g/IAAiHICBAAIAACHgAEig/IAAiHIBhAAIAACHgABrg/IAAiHIB8AAIAACHgAgug/IAAiHIBeAAIAACHgAjSg/IAAiHIBqAAIAACHgAmQg/IAAiHICFAAIAACHgApTg/IAAiHICJAAIAACHgAsCg/IAAiHIB0AAIAACHgAudg/IAAiHIBfAAIAACHgAxVg/IAAiHIB9AAIAACHgAz8g/IAAiHIBtAAIAACHgA2rg/IAAiHIB2AAIAACHgA5ig/IAAiHIB+AAIAACHgA78g/IAAiHIBgAAIAACHgA+zg/IAAiHIB9AAIAACHgEghagA/IAAiHIBsAAIAACHgEgkKgA/IAAiHIB2AAIAACHgEgm4gA/IAAiHIB1AAIAACHgEgpRgA/IAAiHIBgAAIAACHgEgsJgA/IAAiHIB8AAIAACHgEgulgA/IAAiHIBgAAIAACHgEgxegA/IAAiHICAAAIAACHgEgz6gA/IAAiHIBiAAIAACHgEg2xgA/IAAiHIB9AAIAACHgEg6MgA/IAAiHIChAAIAACHgEg9ogA/IAAiHIChAAIAACHgEA6bgFcIAAiLIDOAAIAACLgEA27gFcIAAiLIClAAIAACLgEA0DgFcIAAiLIB9AAIAACLgEAxogFcIAAiLIBhAAIAACLgEAuxgFcIAAiLIB9AAIAACLgEAsLgFcIAAiLIBsAAIAACLgEApcgFcIAAiLIB0AAIAACLgEAmtgFcIAAiLIB1AAIAACLgEAkTgFcIAAiLIBfAAIAACLgEAhagFcIAAiLIB/AAIAACLgAfClcIAAiLIBfAAIAACLgAcGlcIAAiLICBAAIAACLgAZslcIAAiLIBfAAIAACLgAW0lcIAAiLIB9AAIAACLgAUZlcIAAiLIBgAAIAACLgARklcIAAiLIB7AAIAACLgAPKlcIAAiLIBfAAIAACLgAMSlcIAAiLIB9AAIAACLgAJ3lcIAAiLIBhAAIAACLgAG8lcIAAiLICBAAIAACLgAEilcIAAiLIBhAAIAACLgABrlcIAAiLIB8AAIAACLgAgulcIAAiLIBeAAIAACLgAjSlcIAAiLIBqAAIAACLgAmQlcIAAiLICFAAIAACLgApTlcIAAiLICJAAIAACLgAsClcIAAiLIB0AAIAACLgAudlcIAAiLIBfAAIAACLgAxVlcIAAiLIB9AAIAACLgAz8lcIAAiLIBtAAIAACLgA2rlcIAAiLIB2AAIAACLgA5ilcIAAiLIB+AAIAACLgA78lcIAAiLIBgAAIAACLgA+zlcIAAiLIB9AAIAACLgEghagFcIAAiLIBsAAIAACLgEgkKgFcIAAiLIB2AAIAACLgEgm4gFcIAAiLIB1AAIAACLgEgpRgFcIAAiLIBgAAIAACLgEgsJgFcIAAiLIB8AAIAACLgEgulgFcIAAiLIBgAAIAACLgEgxegFcIAAiLICAAAIAACLgEgz6gFcIAAiLIBiAAIAACLgEg2xgFcIAAiLIB9AAIAACLgEg6MgFcIAAiLIChAAIAACLgEg9ogFcIAAiLIChAAIAACLgEA6bgIPIAAiNIDOAAIAACNgEA27gIPIAAiNIClAAIAACNgEA0DgIPIAAiNIB9AAIAACNgEAxogIPIAAiNIBhAAIAACNgEAuxgIPIAAiNIB9AAIAACNgEAsLgIPIAAiNIBsAAIAACNgEApcgIPIAAiNIB0AAIAACNgEAmtgIPIAAiNIB1AAIAACNgEAkTgIPIAAiNIBfAAIAACNgEAhagIPIAAiNIB/AAIAACNgAfCoPIAAiNIBfAAIAACNgAcGoPIAAiNICBAAIAACNgAZsoPIAAiNIBfAAIAACNgAW0oPIAAiNIB9AAIAACNgAUZoPIAAiNIBgAAIAACNgARkoPIAAiNIB7AAIAACNgAPKoPIAAiNIBfAAIAACNgAMSoPIAAiNIB9AAIAACNgAJ3oPIAAiNIBhAAIAACNgAG8oPIAAiNICBAAIAACNgAEioPIAAiNIBhAAIAACNgABroPIAAiNIB8AAIAACNgAguoPIAAiNIBeAAIAACNgAjSoPIAAiNIBqAAIAACNgAmQoPIAAiNICFAAIAACNgApToPIAAiNICJAAIAACNgAsCoPIAAiNIB0AAIAACNgAudoPIAAiNIBfAAIAACNgAxVoPIAAiNIB9AAIAACNgAz8oPIAAiNIBtAAIAACNgA2roPIAAiNIB2AAIAACNgA5ioPIAAiNIB+AAIAACNgA78oPIAAiNIBgAAIAACNgA+zoPIAAiNIB9AAIAACNgEghagIPIAAiNIBsAAIAACNgEgkKgIPIAAiNIB2AAIAACNgEgm4gIPIAAiNIB1AAIAACNgEgpRgIPIAAiNIBgAAIAACNgEgsJgIPIAAiNIB8AAIAACNgEgulgIPIAAiNIBgAAIAACNgEgxegIPIAAiNICAAAIAACNgEgz6gIPIAAiNIBiAAIAACNgEg2xgIPIAAiNIB9AAIAACNgEg6MgIPIAAiNIChAAIAACNgEg9ogIPIAAiNIChAAIAACNgEA6bgLCIAAiyIDOAAIAACygEA27gLCIAAiyIClAAIAACygEA0DgLCIAAiyIB9AAIAACygEAxogLCIAAiyIBhAAIAACygEAuxgLCIAAiyIB9AAIAACygEAsLgLCIAAiyIBsAAIAACygEApcgLCIAAiyIB0AAIAACygEAmtgLCIAAiyIB1AAIAACygEAkTgLCIAAiyIBfAAIAACygEAhagLCIAAiyIB/AAIAACygAfCrCIAAiyIBfAAIAACygAcGrCIAAiyICBAAIAACygAZsrCIAAiyIBfAAIAACygAW0rCIAAiyIB9AAIAACygAUZrCIAAiyIBgAAIAACygARkrCIAAiyIB7AAIAACygAPKrCIAAiyIBfAAIAACygAMSrCIAAiyIB9AAIAACygAJ3rCIAAiyIBhAAIAACygAG8rCIAAiyICBAAIAACygAEirCIAAiyIBhAAIAACygABrrCIAAiyIB8AAIAACygAgurCIAAiyIBeAAIAACygAjSrCIAAiyIBqAAIAACygAmQrCIAAiyICFAAIAACygApTrCIAAiyICJAAIAACygAsCrCIAAiyIB0AAIAACygAudrCIAAiyIBfAAIAACygAxVrCIAAiyIB9AAIAACygAz8rCIAAiyIBtAAIAACygA2rrCIAAiyIB2AAIAACygA5irCIAAiyIB+AAIAACygA78rCIAAiyIBgAAIAACygA+zrCIAAiyIB9AAIAACygEghagLCIAAiyIBsAAIAACygEgkKgLCIAAiyIB2AAIAACygEgm4gLCIAAiyIB1AAIAACygEgpRgLCIAAiyIBgAAIAACygEgsJgLCIAAiyIB8AAIAACygEgulgLCIAAiyIBgAAIAACygEgxegLCIAAiyICAAAIAACygEgz6gLCIAAiyIBiAAIAACygEg2xgLCIAAiyIB9AAIAACygEg6MgLCIAAiyIChAAIAACygEg9ogLCIAAiyIChAAIAACyg");
	this.shape_94.setTransform(624.3,410.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_94},{t:this.shape_93},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.shape_89},{t:this.shape_88}]}).wait(1));

	// side
	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#FEF8F6").s().p("EhAcAHPIjFAAIg8AAIikAAIg8AAIiHAAIg8AAIibAAIg8AAIibAAIg8AAIiHAAIAAhHICHAAIA8AAICbAAIA8AAICbAAIA8AAICHAAIA8AAICkAAIA8AAIDFAAIA8AAIAABHgEBRvAHDIg8AAIibAAIg8AAIibAAIg8AAIiHAAIg8AAIjRAAIg8AAIjQAAIg8AAIAAhHIA8AAIDQAAIA8AAIDRAAIA8AAICHAAIA8AAICbAAIA8AAICbAAIA8AAICHAAIAABHgEhAcADJIjFAAIg8AAIikAAIg8AAIiHAAIg8AAIibAAIg8AAIibAAIg8AAIiHAAIAAhHICHAAIA8AAICbAAIA8AAICbAAIA8AAICHAAIA8AAICkAAIA8AAIDFAAIA8AAIAABHgEBRvAC9Ig8AAIibAAIg8AAIibAAIg8AAIiHAAIg8AAIjRAAIg8AAIjQAAIg8AAIAAhHIA8AAIDQAAIA8AAIDRAAIA8AAICHAAIA8AAICbAAIA8AAICbAAIA8AAICHAAIAABHgEhAcgBIIjFAAIg8AAIikAAIg8AAIiHAAIg8AAIibAAIg8AAIibAAIg8AAIiHAAIAAhGICHAAIA8AAICbAAIA8AAICbAAIA8AAICHAAIA8AAICkAAIA8AAIDFAAIA8AAIAABGgEBRvgBVIg8AAIibAAIg8AAIibAAIg8AAIiHAAIg8AAIjRAAIg8AAIjQAAIg8AAIAAhGIA8AAIDQAAIA8AAIDRAAIA8AAICHAAIA8AAICbAAIA8AAICbAAIA8AAICHAAIAABGgEhAcgF7IjFAAIg8AAIikAAIg8AAIiHAAIg8AAIibAAIg8AAIibAAIg8AAIiHAAIAAhGICHAAIA8AAICbAAIA8AAICbAAIA8AAICHAAIA8AAICkAAIA8AAIDFAAIA8AAIAABGgEBRvgGIIg8AAIibAAIg8AAIibAAIg8AAIiHAAIg8AAIjRAAIg8AAIjQAAIg8AAIAAhGIA8AAIDQAAIA8AAIDRAAIA8AAICHAAIA8AAICbAAIA8AAICbAAIA8AAICHAAIAABGg");
	this.shape_95.setTransform(638.7,448.4);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#7D8894").s().p("EhYrAQcMAAAggrIE2AAIAAETIAADmIAABHIAADsIAABHIAADKIAABHIAAC/IAABHIAAC/IAAHigEBT2AP0IAAnHIAAi/IAAhGIAAjAIAAhGIAAjLIAAhGIAAjtIAAhGIAAjmIAAkTIE2AAMAAAAgPg");
	this.shape_96.setTransform(638.7,456.8);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#D03F33").s().p("EhAcAKiIAAi/IA8AAIAAC/gEhEdAKiIAAi/IA8AAIAAC/gEhH9AKiIAAi/IA8AAIAAC/gEhLAAKiIAAi/IA8AAIAAC/gEhOXAKiIAAi/IA8AAIAAC/gEhRuAKiIAAi/IA8AAIAAC/gEBQzAKVIAAi/IA8AAIAAC/gEBNcAKVIAAi/IA8AAIAAC/gEBKFAKVIAAi/IA8AAIAAC/gEBHCAKVIAAi/IA8AAIAAC/gEBC1AKVIAAi/IA8AAIAAC/gEA+pAKVIAAi/IA8AAIAAC/gEhAcAGcIAAi/IA8AAIAAC/gEhEdAGcIAAi/IA8AAIAAC/gEhH9AGcIAAi/IA8AAIAAC/gEhLAAGcIAAi/IA8AAIAAC/gEhOXAGcIAAi/IA8AAIAAC/gEhRuAGcIAAi/IA8AAIAAC/gEBQzAGPIAAi/IA8AAIAAC/gEBNcAGPIAAi/IA8AAIAAC/gEBKFAGPIAAi/IA8AAIAAC/gEBHCAGPIAAi/IA8AAIAAC/gEBC1AGPIAAi/IA8AAIAAC/gEA+pAGPIAAi/IA8AAIAAC/gEhAcACWIAAjKIA8AAIAADKgEhEdACWIAAjKIA8AAIAADKgEhH9ACWIAAjKIA8AAIAADKgEhLAACWIAAjKIA8AAIAADKgEhOXACWIAAjKIA8AAIAADKgEhRuACWIAAjKIA8AAIAADKgEBQzACJIAAjKIA8AAIAADKgEBNcACJIAAjKIA8AAIAADKgEBKFACJIAAjKIA8AAIAADKgEBHCACJIAAjKIA8AAIAADKgEBC1ACJIAAjKIA8AAIAADKgEA+pACJIAAjKIA8AAIAADKgEhAcgB7IAAjsIA8AAIAADsgEhEdgB7IAAjsIA8AAIAADsgEhH9gB7IAAjsIA8AAIAADsgEhLAgB7IAAjsIA8AAIAADsgEhOXgB7IAAjsIA8AAIAADsgEhRugB7IAAjsIA8AAIAADsgEBQzgCHIAAjtIA8AAIAADtgEBNcgCHIAAjtIA8AAIAADtgEBKFgCHIAAjtIA8AAIAADtgEBHCgCHIAAjtIA8AAIAADtgEBC1gCHIAAjtIA8AAIAADtgEA+pgCHIAAjtIA8AAIAADtgEhAcgGuIAAjmIA8AAIAADmgEhEdgGuIAAjmIA8AAIAADmgEhH9gGuIAAjmIA8AAIAADmgEhLAgGuIAAjmIA8AAIAADmgEhOXgGuIAAjmIA8AAIAADmgEhRugGuIAAjmIA8AAIAADmgEBQzgG6IAAjnIA8AAIAADngEBNcgG6IAAjnIA8AAIAADngEBKFgG6IAAjnIA8AAIAADngEBHCgG6IAAjnIA8AAIAADngEBC1gG6IAAjnIA8AAIAADngEA+pgG6IAAjnIA8AAIAADng");
	this.shape_97.setTransform(638.7,446.4);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#0E0E0E").s().p("EhDhAKiIAAi/IDFAAIAAC/gEhHBAKiIAAi/ICkAAIAAC/gEhKEAKiIAAi/ICHAAIAAC/gEhNbAKiIAAi/ICbAAIAAC/gEhQyAKiIAAi/ICbAAIAAC/gEhT1AKiIAAi/ICHAAIAAC/gEBRvAKVIAAi/ICHAAIAAC/gEBOYAKVIAAi/ICbAAIAAC/gEBLBAKVIAAi/ICbAAIAAC/gEBH+AKVIAAi/ICHAAIAAC/gEBDxAKVIAAi/IDRAAIAAC/gEA/lAKVIAAi/IDQAAIAAC/gEhDhAGcIAAi/IDFAAIAAC/gEhHBAGcIAAi/ICkAAIAAC/gEhKEAGcIAAi/ICHAAIAAC/gEhNbAGcIAAi/ICbAAIAAC/gEhQyAGcIAAi/ICbAAIAAC/gEhT1AGcIAAi/ICHAAIAAC/gEBRvAGPIAAi/ICHAAIAAC/gEBOYAGPIAAi/ICbAAIAAC/gEBLBAGPIAAi/ICbAAIAAC/gEBH+AGPIAAi/ICHAAIAAC/gEBDxAGPIAAi/IDRAAIAAC/gEA/lAGPIAAi/IDQAAIAAC/gEhDhACWIAAjKIDFAAIAADKgEhHBACWIAAjKICkAAIAADKgEhKEACWIAAjKICHAAIAADKgEhNbACWIAAjKICbAAIAADKgEhQyACWIAAjKICbAAIAADKgEhT1ACWIAAjKICHAAIAADKgEBRvACJIAAjKICHAAIAADKgEBOYACJIAAjKICbAAIAADKgEBLBACJIAAjKICbAAIAADKgEBH+ACJIAAjKICHAAIAADKgEBDxACJIAAjKIDRAAIAADKgEA/lACJIAAjKIDQAAIAADKgEhDhgB7IAAjsIDFAAIAADsgEhHBgB7IAAjsICkAAIAADsgEhKEgB7IAAjsICHAAIAADsgEhNbgB7IAAjsICbAAIAADsgEhQygB7IAAjsICbAAIAADsgEhT1gB7IAAjsICHAAIAADsgEBRvgCHIAAjtICHAAIAADtgEBOYgCHIAAjtICbAAIAADtgEBLBgCHIAAjtICbAAIAADtgEBH+gCHIAAjtICHAAIAADtgEBDxgCHIAAjtIDRAAIAADtgEA/lgCHIAAjtIDQAAIAADtgEhDhgGuIAAjmIDFAAIAADmgEhHBgGuIAAjmICkAAIAADmgEhKEgGuIAAjmICHAAIAADmgEhNbgGuIAAjmICbAAIAADmgEhQygGuIAAjmICbAAIAADmgEhT1gGuIAAjmICHAAIAADmgEBRvgG6IAAjnICHAAIAADngEBOYgG6IAAjnICbAAIAADngEBLBgG6IAAjnICbAAIAADngEBH+gG6IAAjnICHAAIAADngEBDxgG6IAAjnIDRAAIAADngEA/lgG6IAAjnIDQAAIAADng");
	this.shape_98.setTransform(638.7,446.4);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#F2F253").s().p("EhT1AQcIAAniICHAAIA8AAICbAAIA8AAICbAAIA8AAICHAAIA8AAICkAAIA8AAIDFAAIA8AAIAAHigEA+pAP0IAAnHIA8AAIDQAAIA8AAIDRAAIA8AAICHAAIA8AAICbAAIA8AAICbAAIA8AAICHAAIAAHHgEhAcgL8IjFAAIg8AAIikAAIg8AAIiHAAIg8AAIibAAIg8AAIibAAIg8AAIiHAAIAAkTIUVAAIAAETgEBRvgMIIg8AAIibAAIg8AAIibAAIg8AAIiHAAIg8AAIjRAAIg8AAIjQAAIg8AAIAAkTIVNAAIAAETg");
	this.shape_99.setTransform(638.7,456.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_99},{t:this.shape_98},{t:this.shape_97},{t:this.shape_96},{t:this.shape_95}]}).wait(1));

	// bg_ground
	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f("#003300").s().p("EibiAMQIAAvTUAaMgEfAoMgCaUAmegCTAshAAAUAseAAAApkACTUArcACaAgQAEfIAAPTg");
	this.shape_100.setTransform(721.5,490.3);

	this.timeline.addTween(cjs.Tween.get(this.shape_100).wait(1));

	// cloud_2 
	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.f("#FFFFFF").s().p("AolCxQgOgKgHgZQgMgsAfglQAKgMAGAAQAdgDARAFIAZASQgZg0AQgcQAQgdAUgGQAUgGAUAIIAjAWQgShnBGgTQBEgSAlAXQAkAXASBLQgEhQAFgHQAXggAngKIAWgGQBjgGAdBYQAEAOgBBBQALhNAggOQArgTAvAAQBaAUAHBYIACAiQAeghAsgHIAWgEIAOAAQDGAbgkCxg");
	this.shape_101.setTransform(443.1,210.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_101).wait(1));

	// cloud_3
	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.f("#FFFFFF").s().p("AodCxQgNgKgIgZQgMgsAfglQAKgMAHAAQAcgDASAFIAYASQgZg0AQgcQAQgdAUgGQAUgGAUAIIAjAWQgShnBGgTQBFgSAkAXQAkAXASBLQgEhQAFgHQAXggAngKIAXgGQBigGAdBYQAEAOgBBBQALhNAggOQArgTAvAAQBaAUAHBYIACAiQAeghAsgHIAWgEIAOAAQCFAlAOBNQAPBNgoANg");
	this.shape_102.setTransform(1192.5,196.6);

	this.timeline.addTween(cjs.Tween.get(this.shape_102).wait(1));

	// cloud_2
	this.shape_103 = new cjs.Shape();
	this.shape_103.graphics.f("#FFFFFF").s().p("AqKEdQhZgHgNhDQgNhDBOgNQAVAAAHAEQAHAEAaAYQgVgvAFgRQAGgcASgTQBehlB5CKIAKgzQAFg0AmgqQBShYB7BuQgRhoAdgmQAug7BUATQARAHAUAOQAiAaAXBSQgChGAOgWQAwhTBggWQCMASAjB/QATBHgtBSQA3gkAtgNQAugNAuARQAuAPAdAnQAJANADARQAHAxglAkQAFgBAHAAQANABANgBQA4ANANAuQANAvg2Aqg");
	this.shape_103.setTransform(833,104.1);

	this.timeline.addTween(cjs.Tween.get(this.shape_103).wait(1));

	// cloud_1
	this.shape_104 = new cjs.Shape();
	this.shape_104.graphics.f("#FFFFFF").s().p("AqkEdQg0gqANgvQAMguA2gNQAMABANgBQAGAAAFABQgkgkAHgxQADgRAJgNQAbgnAsgPQAsgRArANQArANA1AkQgrhSAShHQAhh/CGgSQBbAWAuBTQANAWgCBGQAWhSAhgaQASgOARgHQBQgTArA7QAcAmgQBoQB1huBOBYQAkAqAFA0IAJAzQB0iKBaBlQAQATAHAcQAEARgUAvQAZgYAHgEQAGgEAUAAQBLANgNBDQgNBDhUAHg");
	this.shape_104.setTransform(193,109.8);

	this.timeline.addTween(cjs.Tween.get(this.shape_104).wait(1));

	// sky
	this.shape_105 = new cjs.Shape();
	this.shape_105.graphics.f("#8ABCD5").s().p("EiaZA5VMAAAhypME0yAAAMAAABypg");
	this.shape_105.setTransform(717.4,281.8);

	this.timeline.addTween(cjs.Tween.get(this.shape_105).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(66.2,274.8,2437,925);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;